<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- bxSlider Javascript file -->
<script src="<?= $this->baseUrl() ?>/bxslider/jquery.bxslider.js"></script>
<!-- bxSlider CSS file -->
<link href="<?= $this->baseUrl() ?>/bxslider/jquery.bxslider.css" rel="stylesheet" />
<script>
$(document).ready(function(){

  $('.slider2').bxSlider({
    slideWidth: 290,
    minSlides: 2,
    maxSlides: 3,
    slideMargin: 10
  });
 


});
  </script>


<div class="banner" style="margin-top: -5% !important">
  <div class="full-container">
    <div class="slider-content">
      <ul id="pager2" class="container">
<!--        <span class="">•</span>-->
      </ul>
      <!-- prev/next links --> 
      
      <span class="prevControl sliderControl"> 
          <i class="fa fa-angle-left fa-3x "></i>
      </span> <span class="nextControl sliderControl"> 
          <i class="fa fa-angle-right fa-3x "></i>
      </span>
      <div class="slider slider-v1" data-cycle-swipe="true" data-cycle-prev=".prevControl" data-cycle-next=".nextControl" data-cycle-loader="wait" style="overflow: hidden;">
<!--          <div class="slider-item slider-item-img1 cycle-slide cycle-sentinel" style="visibility: hidden; position: static; top: 0px; left: 0px; z-index: 100; opacity: 1; display: block;"> 
              <img src="images/slider/slider0.jpg" class="img-responsive parallaximg sliderImg" alt="img" style="visibility: hidden;"> 
          </div>
        -->
        
        <!--/.slider-item-->
 <?php foreach($this->slides as $slide){?>
        <div class="slider-item slider-item-img3  cycle-slide" style="visibility: hidden; position: absolute; top: 0px; left: 0px; z-index: 96; opacity: 1; display: block;">
          <div class="sliderInfo">
            <div class="container">
              <div class="col-lg-5 col-md-4 col-sm-6 col-xs-8   pull-left sliderText white hidden-xs">
                <div class="inner">
                  <h1>Закажите услугу</h1>
                  <h3 class="price ">
                      Мы быстро найдем исполнителя для Вашего задания
                  </h3>
                  
                  <a  href="<?= $this->baseUrl().'/customer/task/new-task'?>"class="btn btn-primary btn-lg">
                      Заказать услугу
                      <span class="arrowUnicode">►</span>
                  </a> 
                </div>
              </div>
            </div>
          </div>
          <img src="<?=  $this->baseUrl().'/images/main-banner/'.$slide['image'] ?>" class="img-responsive parallaximg sliderImg" alt="img"> 
        </div>
 <?php } ?>
      </div>
      <!--/.slider slider-v1--> 
    </div>
    <!--/.slider-content--> 
  </div>
  <!--/.full-container--> 
</div>

<div class="container main-container"> 
  <div class="row subCategoryList clearfix">
    <?php foreach($this->mainCats as $cat){?>
    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-6  text-center">
      <div class="thumbnail equalheight" style="height: 190px;">
          <a class="subCategoryThumb" href="<?= $this->baseUrl().'/customer/task/new-task'?>" style="height:150px; padding-top: 10px">
              <img src="<?= $this->baseUrl().'/images/category_images/'.$cat['image'] ?>" class="img-rounded " alt="img">
          </a>
          <a class="subCategoryTitle" href="<?= $this->baseUrl().'/customer/task/new-task'?>" >
              <span><?= $cat['title'] ?></span>
          </a>
      </div>
    </div>
    <?php } ?>
</div>
</div>

  <!-- Main component call to action -->
  
  <div class="morePost row featuredPostContainer style2 globalPaddingTop ">
    <h3 class="section-title style2 text-center"><span>Архив задач</span></h3>
    <div class="container">
      <div class="row xsResponse">
          
       <?php foreach($this->lastTasks as $lastTask){?>
      <!--/.item-->
        <div class="item col-lg-3 col-md-3 col-sm-4 col-xs-6 productBlock list-view">

            <div class="col-sm-2">
               <a href="<?= $this->baseUrl().'/customer/task/view/id/'.$lastTask['id'] ?>" >
               <?php if($lastTask['task_image']){?> 
                   <div style="background: center no-repeat url('<?= $this->baseUrl().'/images/task_images/'.$lastTask['task_image'] ?>'); height:122px; width: 160px; background-size: contain; margin-top: 15px" src="" alt="img" class="img-thumbnail img-responsive"></div>     
                  
               <?php }else{ ?>
                   <div style="background: center no-repeat url('<?= $this->baseUrl().'/images/task_images/no-image.png' ?>'); height:122px; width: 160px; background-size: contain; margin-top: 15px" src="" alt="img" class="img-thumbnail img-responsive"></div>     
               <?php } ?>   
              </a>
            </div>
            <div class="col-sm-10">
                <div class="col-sm-9">                
                    <h4 style="margin-top: 15px !important"><a href="<?= $this->baseUrl().'/customer/task/view/id/'.$lastTask['id'] ?>" ><?= $lastTask['title'] ?></a></h4>
                </div>
                <div class="col-sm-3">                
                    <h4 style="margin-top: 15px !important"> <span><?= $lastTask['price'] ?> бел. рублей</h4>
                </div>
                <div class="col-sm-12"> 
                    <small>Дата исполнения: <?= date( "d.m.Y" ,$lastTask['final_date']) ?> </small>
                </div>
                <div class="col-sm-12"> 
                    <p><?= $lastTask['description']?> </p>
                </div>
            
                <div class="col-sm-9"> 
                    </div>
                <div class="col-sm-3"> 
                    <div class="action-control"> <a class="btn btn-primary" href="<?= $this->baseUrl().'/customer/task/view/id/'.$lastTask['id'] ?>"> <span class="add2cart"> Подробнее </span> </a> </div>
                </div>
              </div>

        </div>
       <?php }?>
        
        <!--/.item--> 
      </div>
      <!-- /.row -->
      
      <div class="row">
        <div class="load-more-block text-center">  </div>
      </div>
    </div>
    <!--/.container--> 
  </div>
  <!--/.featuredPostContainer-->
  


  <!--/.section-block-->
  
 
  
</div>
