<section id="content">
    <div class="container">
        <div class="sixteen columns">
          <div class="divider"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="container">
        <a href="<?= $this->vkLink ?>">VK.com</a></br>
        <a href="<?= $this->fbLink ?>">facebook.com</a></br>
        <a href="<?= $this->okLink ?>">OK.RU</a></br>

    </div>        
</section>