
<html lang="en"><head>
<!--    <meta charset="utf-8">-->
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

   <?php echo $this->headTitle(); ?>

    <!-- Bootstrap core CSS -->
    <link href="<?= $this->baseUrl() ?>/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?= $this->baseUrl() ?>/bootstrap/css/blog.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
            
        <?php if(Zend_Auth::getInstance()->hasIdentity()){?>
                          
            <a class="blog-nav-item" href="http://icando.dev.skilus.biz/authentication/log-out" >Выйти</a>
                           
         <?php }else{ ?>
            <a class="blog-nav-item" href="<?php echo $this->url(array('controller'=>'registration', 'action'=>'index'))?>" >Регистрация</a> 
            <a class="blog-nav-item" href="<?php echo $this->url(array('controller'=>'s-auth', 'action'=>'index'))?>" >Авторизация через соцсети</a> 
            <a class="blog-nav-item" href="<?php echo $this->url(array('controller'=>'authentication', 'action'=>'log-in'))?>" >Войти</a> 
        <?php }?>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title"><?php echo $this->headTitle(); ?>  </h1>
        
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">

         <?php echo $this->layout()->content; ?>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <ol class="list-unstyled">
                Меню
                
                <li>
                   <a href="#">Подать заявку на исполнителя</a>
                </li>
            </ol>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>iCanDo </p>
      <p>
        <a href="#">Вверх</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="<?= $this->baseUrl() ?>/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?= $this->baseUrl() ?>/bootstrap/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="<?= $this->baseUrl() ?>/bootstrap/js/ie10-viewport-bug-workaround.js"></script>
  

</body></html>