
<!--        <div>
           <?php //echo $this->form;?>
        </div>-->
                    <div class="page-splash" id="serviceList" style="height : 299px;">
                        <div class="inner" >
                    <div class="container">
                                <div class="sixteen columns">
                                    <h2 class="title">
                                        Оставить отзыв
                                    </h2>
                                  
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                    <div class="container">
                        <div class="row-indent">
                            <div class="portfolio-page-container">
                                <div class="container">
                                    <div class="sixteen columns marg-bott-cont">
                                    </div>
                                    <div class="clear"></div>
                                </div>
                                <div class="portfolio-container" id="new-feedback">
                                    <div class="container">
                                        
                                <?= $this->form;?>
                                        
                                    <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                           
                            <div class="clearfix"></div>
                        </div>
                    </div>
               <div class="sixteen columns">
                <div class="divider"></div>
               </div>

        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery-2.0.0.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery-migrate-1.1.1.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/raphael-min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.validationEngine.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.validationEngine-en.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.form.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.hoverdir.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.selectik.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.isotope.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/touchTouch.jquery.js"></script>
        <script src="http://twitterjs.googlecode.com/svn/trunk/src/twitter.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.carouFredSel-6.2.1.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/tabs.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/toggles.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/boxes.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/settings-panel.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.cookie.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/script.js"></script>
<script >
$(document).ready(function(){
   $('#feedback').attr('height', 87);
   //remove class
   $('#index').removeClass('active');
   $('#services').removeClass('active');
   $('#gallery').removeClass('active');
   $('#contacts').removeClass('active');
   //add
   $('#feedback').addClass('active');
});
</script>