
       
 
                                 <div  id="edit-service">
                                    <div class="container">

 <?= $this->form;?>
                                        <div class="clearfix"></div>

                                    </div>
                                </div></br>     
        
 <script src="<?= $this->baseUrl() ?>/desktop/js/jquery-2.0.0.min.js"></script>       
        
        
        <script type="text/javascript">
             CKEDITOR.replace( 'description' );
        </script>
         <script type="text/javascript">
$(document).ready(function(){
   //remove class
   $('#index').removeClass('active');
   $('#gallery').removeClass('active');
   $('#contacts').removeClass('active');
   $('#feedback').removeClass('active');
   //add
   $('#services').addClass('active');
});
</script>        