<div class="container main-container"> 
  
  <!-- Main component call to action -->
  
  <div class="morePost row featuredPostContainer style2 globalPaddingTop ">
    <h3 class="section-title style2 text-center"><span>Последние задачи</span></h3>
    <div class="container">
      <div class="row xsResponse">
       <?php foreach($this->lastTasks as $lastTask){?>
        <!--/.item-->
        <div class="item col-lg-3 col-md-3 col-sm-4 col-xs-6">
          <div class="product">
         
            <div class="image">  
             <div class="quickview">
              
             </div><a href="#" data-toggle="modal" data-target="#ModalLogin" ><img src="<?= $this->baseUrl().'/images/task_images/'.$lastTask['task_image'] ?>" alt="img" class="img-responsive"></a>
<!--              <div class="promotion"> <span class="new-product"> NEW</span> </div>-->
            </div>
            <div class="description">
              <h4><a href="#" data-toggle="modal" data-target="#ModalLogin" ><?= $lastTask['title'] ?></a></h4>
              <p><?= $lastTask['description']?> </p>
<!--              <span class="size">XL / XXL / S </span> -->
            </div>
            <div class="price"> <span><?= $lastTask['price'] ?> .руб</span> </div>
            <div class="action-control"> <a class="btn btn-primary" data-toggle="modal" data-target="#ModalLogin" > <span class="add2cart"> Подробнее </span> </a> </div>
          </div>
        </div>
       <?php }?>
        <!--/.item--> 
      </div>
      <!-- /.row -->
      
      <div class="row">
        <div class="load-more-block text-center">  </div>
      </div>
    </div>
    <!--/.container--> 
  </div>
  <!--/.featuredPostContainer-->
  
  <hr class="no-margin-top">

  <!--/.section-block-->
  
 
  
</div>