
        <?php if(!$this->tasks){?>
        <div class="col-lg-12">
            <h3>Задач не найдено</h3>
        </div>
        <?php }else{ ?>
        <div class="col-lg-12">
            <h3>Задачи</h3>
        </div>
        <table id="taskTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Название</th>
                <th>Заказчик</th>
                <th>Дата исполнения</th>
                <th>Дата создания</th>
                <th>Цена</th>
            </tr>
        </thead>    

        <tbody>
    <?php foreach($this->tasks as $task){?>
            <tr id="div<?= $customer['id'] ?>">
                <td><a href="<?= $this->baseUrl() ?>/performer/task/view/id/<?= $task['id'] ?>"><?= $task['title'] ?></td>
                <td><a href="<?= $this->baseUrl()?>/performer/customer/view/id/<?= $task['customer_id'] ?>"><?= $task['c_username'].' '.$task['c_surname'] ?></a></td>
                <td><?= date("d.m.Y", $task['final_date']) ?></td>
                <td><?= date("h:i d.m.Y", $task['created_at']) ?></td>
                <td><?= $task['customers_price'] ?></td>
            </tr>

    <?php } ?>
 </tbody>
</table>
        <?php } ?>

<script>
$(document).ready(function(){
   $('#taskTable').DataTable();
});
</script>