<div class="col-lg-12 col-md-12 col-sm-12">
      <div class="w100 clearfix category-top">
        <h2> Исполнители </h2>
        
      </div>

      <!--/.subCategoryList-->
 <?php if($this->performers){?>
      <div class="w100 productFilter clearfix">
        <div class="pull-right ">
            <div class="change-order pull-left">
              <select class="form-control selectpicker" onchange="changeSortOption()"  name="category" id="categorySelect">
                <option value="0" selected="selected">Все категории</option>
                  <?php foreach($this->categories as $category){?>
                          <option value="<?= $category['id'] ?>" <?php if($this->ctegoryId == $category['id']){?> selected <?php } ?>><?= $category['title'] ?></option>
                
                <?php } ?> 
              </select>
            </div>
          <div class="change-view pull-right">
              <a href="#" title="List" id="listView" class="list-view">
                  <i class="fa fa-th-list"></i>
              </a> 
              <a href="#" title="Grid" class="grid-view">
                  <i class="fa fa-th-large"></i>
              </a>
              
          </div>
        </div>
      </div>
      <!--/.productFilter-->
      <div class="row  categoryProduct xsResponse clearfix">
          <?php if(!empty($this->performers)){?>
        <?php foreach($this->performers as $performer){?>  
         
            <div class="item col-sm-4 col-lg-4 col-md-4 col-xs-6 list-view">
              <div class="product">

                <div class="image">  
                    <a href="<?= $this->baseUrl().'/performer/performers/performer-view/id/'.$performer['u_id']  ?>">
                        <img src="<?= $this->baseUrl().'/images/users_images/'.$performer['u_image'] ?>" style="max-height: 110px" class="img-responsive img-thumbnail" alt="img" >
                    </a>
                    
                </div>
                <div class="description">
                    <?php  
                        $tasksObj = new Performer_Model_DbTable_TasksModel();
                        $tasksAmount = count($tasksObj->getPerformersTasks($performer['u_id']));
                        if($tasksAmount > 0){
                            $feedbackObj = new Performer_Model_DbTable_FeedbackModel();
                            $rating = $feedbackObj->countPerformersRating($performer['u_id']);       
                    ?>
                    <ul class="swatches Color">
                    <?php switch ($rating){
                        case 1:?>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <?php break;
                        case 2:
                ?>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                  <?php
                  break;
                  case 3: ?>  
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                  <?php break;
                        case 4:
              ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <?php break;
                        case 5:
              ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                       <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                    <?php 
                    break;
                    default: ?>
                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                        <?php } }?>
                  </ul>
                  <h4>
                      
                        <a href="<?= $this->baseUrl().'/performer/performers/performer-view/id/'.$performer['u_id']  ?>">
                            <?= $performer['u_username'].' '.mb_substr($performer['u_surname'], 0, 1, 'utf-8').'.' ?>
                        </a>
                  </h4>
                    <small>Выполненных задач : <?= $tasksAmount ?></small>
                  
<!--                    <div class="grid-description">-->
                        <p><?= $performer['u_about'] ?></p>
<!--                    </div>-->
              </div>
<!--                <div class="price"> <span><? $this->task['customers_price'] ?> </span>руб </div>-->
<!--                <div class="action-control"> 
                    
                        <a class="btn btn-primary" href="<?= $this->baseUrl().'/performer/performers/performer-view/id/'.$performer['u_id'] ?>"> 
                            <span class="add2cart">
                                Подробнее
                            </span> 
                        </a> 
                </div>-->
              </div>
            </div>
        <?php } ?>
        <?php }else{ ?>
          <h4>Исполнителей по данной категории пока нет</h4>
        <?php } ?>
        <!--/.item-->
      </div>
      <!--/.categoryProduct || product content end-->
      
      <div class="w100 categoryFooter">
        <div class="pagination pull-left no-margin-top">
          <?=  $this->paginationControl($this->performers, 'Sliding', 'pagination.phtml') ?>
        </div>
        <div class="pull-right pull-right col-sm-4 col-xs-12 no-padding text-right text-left-xs">
          
        </div>
      </div>
      <!--/.categoryFooter--> 
 <?php }else{?>
      <div class="col-sm-12">
          <h3>Открытых задач пока нет</h3>
      </div>    
 <?php } ?>     
    </div>
<script>
function changeSortOption(){
    var category = $('#categorySelect :selected').val();
    window.location.href = '<?= $this->baseUrl() ?>/performer/performers/index/categoryId/'+category+'/';
    
}
</script>