
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
          <li> <a href="<?= $this->baseUrl().'/performer/' ?>">Главная</a> </li>
          <li> <a href="<?= $this->baseUrl().'/performer/user/' ?>">Личный кабинет</a> </li>
        <li class="active"><?= $this->performer['username'].' '.$this->performer['surname'] ?> </li>
      </ul>
    </div>
  </div>
  <div class="row transitionfx"> 
    
    <!-- left column -->
    <div class="col-lg-6 col-md-6 col-sm-6"> 
      <!-- product Image and Zoom -->
      
      <div class="main-image sp-wrap col-lg-12 no-padding style3" style="display: inline-block;">
          <div class="sp-large">
              
                  <img src="<?= $this->baseUrl().'/images/users_images/'.$this->performer['image'] ?>" class="img-responsive" alt="img">
              
          </div>
      </div>
    </div>
    <!--/ left column end --> 
    
    <!-- right column -->
    <div class="col-lg-6 col-md-6 col-sm-5">
      <h1 class="product-title"><?= $this->performer['username'].' '.$this->performer['surname'] ?></h1>
      <?php $sec = time()-$this->performer['birth_date'];
            $age = $sec/31556926;
            $age = floor($age);
      ?>
      <h3 class="product-code">Возраст : <?= $age; ?> лет</h3>
      <?php
      if($this->closedTasks){
         $closedTasksAmount = count($this->closedTasks);
      
      ?>
      <?php if($closedTasksAmount){ ?>
        <h3 class="product-code"> Выполненных работ: <span class="price-sales"><?= $closedTasksAmount ?></span> </h3>
      <?php }else{ ?>
        <h3 class="product-code"> Пользователь еще не завершил ни одного задания</h3>
      <?php } 
      } ?>
      <div class="details-description">
          <h3 class="product-code">Сферы деятельности :</h3>
          
              <?php foreach($this->usersCategories as $cat){?>
                <p><?= $cat['c_title'].' '; ?></p>
              <?php } ?>
          
      </div>
      <?php if($this->closedTasks){ ?>
      <div class="color-details"> <span class="selected-color"><strong>Рейтинг</strong></span>
        <ul class="swatches Color">
          <?php switch ($this->rating){
              case 1:?>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
          <?php break;
              case 2:
      ?>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
        <?php
        break;
        case 3: ?>  
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
        <?php break;
              case 4:
    ?>      <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
          <?php break;
              case 5:
    ?>      <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
          <?php 
          break;
          default: ?>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <?php }?>
        </ul>
      </div>
      <?php } ?>
      <!--/.color-details-->

      
      <div class="clear"></div>

      <!--/.product-tab-->
      
      <div style="clear:both"></div>
      <?php if($this->performer['vk'] || $this->performer['ok'] || $this->performer['fb']){?>
      <div class="product-share clearfix">
        <p> Привязка к соцсетям </p>
        <div class="socialIcon">
            <?php if($this->performer['vk']){?>
                <img src="<?= $this->baseUrl().'/ico/vk.png' ?>" height="50px">
            <?php } if($this->performer['ok']){?>
                <img src="<?= $this->baseUrl().'/ico/ok.png' ?>" height="50px">
            <?php } if($this->performer['fb']){?>
                <img src="<?= $this->baseUrl().'/ico/fb.png' ?>" height="50px">
            <?php }?>
        </div>
      </div>
      <?php } ?>
      <!--/.product-share--> 
      
    </div>
    <!--/ right column end --> 
    
  </div>
  <!--/.row-->

  <!--/.recommended-->
  
  <div style="clear:both"></div></br>
