<?php if($this->performer['role'] == 'performer'){ ?>
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
          <li> <a href="<?= $this->baseUrl().'/performer/' ?>">Главная</a> </li>
          <li> <a href="<?= $this->baseUrl().'/performer/user/' ?>">Личный кабинет</a> </li>
        <li class="active"><?= $this->performer['username'].' '.$this->performer['surname'] ?> </li>
      </ul>
    </div>
  </div>
  <div class="row transitionfx"> 
    
    <!-- left column -->
    <div class="col-lg-4 col-md-4 col-sm-4"> 
      <!-- product Image and Zoom -->
      
      <div class="main-image sp-wrap col-lg-12 no-padding style3" style="display: inline-block;">
          <div class="sp-large">
              
                  <img src="<?= $this->baseUrl().'/images/users_images/'.$this->performer['image'] ?>" class="img-responsive" alt="img">
              
          </div>
      </div>
    </div>
    <!--/ left column end --> 
    
    <!-- right column -->
    <div class="col-lg-8 col-md-8 col-sm-8">
        <div class="col-sm-4">
            <h1 class="product-title"><?= $this->performer['username'].' '.$this->performer['surname'] ?></h1>
        </div>
              <?php $sec = time()-$this->performer['birth_date'];
            $age = $sec/31556926;
            $age = floor($age);
      ?>
        <div class="col-sm-8">
  <?php if($closedTasksAmount){ ?>
                       <ul class="swatches Color">
          <?php switch ($this->rating){
              case 1:?>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <?php break;
              case 2:
      ?>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
        <?php
        break;
        case 3: ?>  
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
        <?php break;
              case 4:
    ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <?php break;
              case 5:
    ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
             <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
          <?php 
          break;
          default: ?>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <?php }?>
        </ul>
  
      <?php } ?>
        </div>
        <div class="col-sm-12">
            <h3 class="product-code">Возраст : <?= $age; ?> лет</h3>
         </div>
         <div class="col-sm-12">
      <?php
      if($this->closedTasks){
         $closedTasksAmount = count($this->closedTasks);
      
      ?>
       
      <?php if($closedTasksAmount){ ?>
        <h3 class="product-code"> Выполненных работ: <span class="price-sales"><?= $closedTasksAmount ?></span> </h3>
      <?php }else{ ?>
        <h3 class="product-code"> Пользователь еще не завершил ни одного задания</h3>
      <?php
      } 
      }
      ?>
        </div>
      <div class="details-description col-sm-12">
          <h3 class="product-code">Сферы деятельности :</h3>
          
              <?php foreach($this->usersCategories as $cat){?>
                <small><?= $cat['c_title'].' '; ?></small></br>
              <?php } ?>
          
      </div>
    
      <!--/.color-details-->

      
      <div class="clear"></div>

      <!--/.product-tab-->
      
      <div style="clear:both"></div>
      <?php if($this->performer['vk'] || $this->performer['ok'] || $this->performer['fb']){?>
      <div class="product-share clearfix col-sm-12">
        <p> Привязка к соцсетям </p>
        <div class="socialIcon">
            <?php if($this->performer['vk']){?>
                <img src="<?= $this->baseUrl().'/ico/vk.png' ?>" height="50px">
            <?php } if($this->performer['ok']){?>
                <img src="<?= $this->baseUrl().'/ico/ok.png' ?>" height="50px">
            <?php } if($this->performer['fb']){?>
                <img src="<?= $this->baseUrl().'/ico/fb.png' ?>" height="50px">
            <?php }?>
        </div>
      </div>
      <?php } ?>
      <!--/.product-share--> 
      
    </div>
    <!--/ right column end --> 
    <?php if($this->performer['about']){?>
    <div class="col-lg-12" style="padding-bottom: 10px">
        <h3 class="block-title-3">
                Дополнительная информация  
        </h3>
        <p><?= $this->performer['about'] ?></p>
    </div>
    <?php } ?>
    <!--/ right column end --> 
    <?php if($this->feedbacks){?>
        <div class="col-lg-12" style="padding-bottom: 10px">
            <h3 class="block-title-3">
                Отзывы  
            </h3>
            <?php foreach($this->feedbacks as $feedback){?>
            <div class="col-sm-12">
            <div class="col-lg-3"> 
                <?php if($feedback['kind'] == 'negative'){ ?>
                        <p class="text-danger">Отрицательный</p>
                <?php }else{?>
                        <p class="text-success">Положительный</p>
                        <span class="selected-color"><strong>Оценка</strong></span>
                                <ul class="swatches Color">
                                    <?php switch ($feedback['rating']){
                                        case 1:?>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <?php break;
                                        case 2:
                                ?>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                  <?php
                                  break;
                                  case 3: ?>  
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                  <?php break;
                                        case 4:
                              ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <?php break;
                                        case 5:
                              ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                       <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                    <?php 
                                    break;
                                    default: ?>
                                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <?php }?>
                                  </ul>
                                  <?php } ?>

            </div>
            <div class="col-lg-2">
                <img class="img-thumbnail" width="100%" src="<?= $this->baseUrl().'/images/users_images/'.$feedback['u_image'] ?>">
            </div>
            <div class="col-lg-7"> 
                <h2><?=  $feedback['u_username']?></h2>
                    <p><?= $feedback['text'] ?></p>
                    <h3 class="product-code"><?= date("d.m.Y",$feedback['created']); ?></h3>
            </div>
            </div>
            <?php } ?>
            <?=  $this->paginationControl($this->feedbacks, 'Sliding', 'pagination.phtml') ?>
        </div>
    <?php } ?>
  </div>
  <!--/.row-->

  <!--/.recommended-->
 <?php }else{?>
<div class="row">
    <h2>Просмотр недоступен</h2>
</div>
<?php } ?> 
  <div style="clear:both"></div></br>
