<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

   <?=  $this->headTitle(); ?>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    
    <script src="<?= $this->baseUrl() ?>/datatable/js/datatable.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="<?= $this->baseUrl() ?>/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/smoothness/jquery-ui.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
    <!-- Custom styles for this template -->
    <link href="<?= $this->baseUrl() ?>/bootstrap/css/blog.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/datatable/css/datatable.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
            
            <a class="blog-nav-item" href="<?= $this->baseUrl().'/admin/tasks/' ?>">Задачи</a>
            <a class="blog-nav-item" href="<?= $this->baseUrl().'/admin/messages/' ?>">Сообщения</a>
            <a class="blog-nav-item" href="<?= $this->baseUrl().'/admin/comments/' ?>">Комментарии</a>
          <div class="btn-group">
                 <a class="btn dropdown-toggle blog-nav-item" data-toggle="dropdown" href="#">
                     Категории
                 <span class="caret"></span>
                 </a>
                 <ul class="dropdown-menu">
                   <li><a tabindex="-1" href="<?= $this->url(array('controller' => 'category', 'action' => 'index'))?>">Список</a></li>
                   <li><a tabindex="-1" href="<?= $this->url(array('controller' => 'category', 'action' => 'add-category'))?>">Добавить категорию</a></li>
                 </ul>
          </div>
          <div class="btn-group">
                 <a class="btn dropdown-toggle blog-nav-item" data-toggle="dropdown" href="#">
                     Исполнители
                 <span class="caret"></span>
                 </a>
                 <ul class="dropdown-menu">
                   <li><a tabindex="-1" href="<?= $this->url(array('controller' => 'performers', 'action' => 'index'))?>">Список</a></li>
                   <li><a tabindex="-1" href="<?= $this->url(array('controller' => 'performers', 'action' => 'add'))?>">Добавить исполнителя</a></li>
                 </ul>
          </div>
          <div class="btn-group">
                 <a class="btn dropdown-toggle blog-nav-item" data-toggle="dropdown" href="#">
                     Заказчики
                 <span class="caret"></span>
                 </a>
                 <ul class="dropdown-menu">
                   <li><a tabindex="-1" href="<?= $this->url(array('controller' => 'customers', 'action' => 'index'))?>">Список</a></li>
                   <li><a tabindex="-1" href="<?= $this->url(array('controller' => 'customers', 'action' => 'add'))?>">Добавить исполнителя</a></li>
                 </ul>
          </div>
          <div class="btn-group">
                 <a class="btn dropdown-toggle blog-nav-item"  href="<?= $this->url(array('controller' => 'applications', 'action' => 'index'))?>">Заявки</a>
                 
          </div>
          <div class="btn-group">
                 <a class="btn dropdown-toggle blog-nav-item" href="<?= $this->baseUrl().'/default/authentication/log-out'?>">Выход</a>
          </div>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h3 class="blog-title"><?php echo $this->title; ?>  </h3>
        
      </div>

      <div class="row">



         <?php echo $this->layout()->content; ?>




      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>iCanDo </p>
      <p>
        <a href="#">Вверх</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?= $this->baseUrl() ?>/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?= $this->baseUrl() ?>/bootstrap/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="<?= $this->baseUrl() ?>/bootstrap/js/ie10-viewport-bug-workaround.js"></script>
  

</body></html>