                    
    <div class="row">
        <div class="breadcrumbDiv col-lg-12">
              <ul class="breadcrumb">
                  <li> <a href="<?= $this->baseUrl() ?>">Главная</a> </li>
                 <li class="active" >Личный кабинет</li>
              </ul>
        </div>
    </div>
    <div class="row transitionfx">
  
   <!-- left column -->
    <div class="col-lg-6 col-md-6 col-sm-6">
    	<!-- product Image and Zoom -->

    <div class="main-image sp-wrap col-lg-12 no-padding style2 style2look2" style="display: inline-block;"> 
         
        
         
    <div class="sp-large" style="left: 0px; top: 0px;">
            <img width="100%" src="<?= $this->baseUrl() ?>/images/users_images/<?= $this->user['image'] ?>" class="img-responsive" alt="img" />

    </div>
    </div>
    </div><!--/ left column end -->
    
    
    <!-- right column -->
    <div class="col-lg-6 col-md-6 col-sm-5">
    
      <h1 class="product-title"><?= $this->user['username']." ".$this->user['surname']?></h1>
      <h3 class="product-code">Возраст : <?php $unixAge = time() - $this->user['birth_date'];
                $unixYears = $unixAge/31536000;
                $age = floor($unixYears);
                ?>
                <?= $age;  ?> лет
      </h3>
      <div class="product-price"> 
          <input type="text" id="sum">
          <button onclick="fillBalance()" id="balanceButton" class="btn btn-primary xs3Response">пополнить баланс</button>
          <img id="balancePrel" src="<?= $this->baseUrl().'/images/blue_preloader.gif' ?>" width="60" style="display: none">
      </div>
      <div class="product-price"> 
          <span class="price-sales">
              Создано задач:  <?php $customersTasksAmount = count($this->customersTasks); ?></span> 
              <?= $customersTasksAmount; ?>
           
      </div>
      <div class="product-price"> 
          <span class="price-sales">
              Статус:</span> 
            <?php if($this->user['banned']){?>
             Забанен до <?= date('d.m.y', $this->user['banned']); ?> 
            <?php }else{ ?>
             Активен
            <?php } ?> 
           
      </div>
      <div class="product-price"> 
          <span class="price-sales">
              Баланс:</span> 
              <span id="balSpan"><?= $this->user['balance']; ?></span> баллов
           
      </div>
      <div class="product-price"> 
          <span class="price-sales">
              Выполнено задач:  <?php $performersTasksAmount = count($this->performersTasks); ?>
              <?= $performersTasksAmount; ?>
          </span>  
      </div>
<!--      <div class="color-details"> -->

      <?php if($this->customersRating){ ?>
      <div class="color-details"> <span class="selected-color"><strong>Рейтинг заказчика</strong></span>
        <ul class="swatches Color">
          <?php switch ($this->customersRating){
              case 1:?>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
          <?php break;
              case 2:
      ?>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
        <?php
        break;
        case 3: ?>  
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
        <?php break;
              case 4:
    ?>      <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
          <?php break;
              case 5:
    ?>      <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
          <?php 
          break;
          default: ?>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <?php }?>
        </ul>
      </div>
      <?php } ?>
      
      <div class="clear"></div>

      
      <div style="clear:both"></div>
      <?php if($this->performersRating){ ?>
      <div class="color-details"> <span class="selected-color"><strong>Рейтинг исполнителя</strong></span>
        <ul class="swatches Color">
          <?php switch ($this->performersRating){
              case 1:?>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
          <?php break;
              case 2:
      ?>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
        <?php
        break;
        case 3: ?>  
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
        <?php break;
              case 4:
    ?>      <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li > <a style="background-color:#adadad"> </a> </li>
          <?php break;
              case 5:
    ?>      <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
            <li> <a style="background-color:#f1f40e"> </a> </li>
          <?php 
          break;
          default: ?>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <li > <a style="background-color:#adadad"> </a> </li>
          <?php }?>
        </ul>
      </div>
      <?php } ?>
      
      <div class="clear"></div>

      
      <div style="clear:both"></div>
      <div class="product-share clearfix">
        <p> Привязка к соцсетям </p>
        <div class=""> 
            <?php if(!$this->user['fb']){?>
                <a href="<?= $this->baseUrl().'/social-attach/fb-link/' ?>" data-toggle="tooltip" data-placement="left" title="Нажмите для привязки своего аккаунта" >
                    <img width="30px" src="<?= $this->baseUrl().'/ico/fb_wb.png' ?>" >
                </a> 
            <?php }else{ ?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан" width="40px" src="<?= $this->baseUrl().'/ico/fb.png' ?>" >
            <?php } ?>
            <?php if(!$this->user['ok']){?>
                <a href="<?= $this->baseUrl().'/social-attach/ok-link/' ?>" data-toggle="tooltip" data-placement="left" title="Нажмите для привязки своего аккаунта">
                    <img width="30px" src="<?= $this->baseUrl().'/ico/ok_wb.png' ?>">
                </a> 
            <?php }else{ ?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан" width="40px" src="<?= $this->baseUrl().'/ico/ok.png' ?>" >
            <?php } ?>
            <?php if(!$this->user['vk']){?>
                <a href="<?= $this->baseUrl().'/social-attach/vk-link/' ?>"  data-toggle="tooltip" data-placement="left" title="Нажмите для привязки своего аккаунта">
                    <img width="30px" src="<?= $this->baseUrl().'/ico/vk_wb.png' ?>">
                </a>
            <?php }else{ ?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан"  width="40px" src="<?= $this->baseUrl().'/ico/vk.png' ?>" >
            <?php } ?>
        </div>
      </div>
      
    </div><!--/ right column end -->

  </div>
    <div class="row">
        <div calss="col-lg-12" style="padding-bottom: 5px; padding-top:5px">
<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#orders" aria-controls="orders" role="tab" data-toggle="tab">Принятые заказы</a></li>
    <li role="presentation"><a href="#tasks" aria-controls="tasks" role="tab" data-toggle="tab">Мои задачи</a></li>
    <?php if($this->userPrepositions){?>
        <li role="presentation"><a href="#app" aria-controls="app" role="tab" data-toggle="tab">Мои заявки</a></li>
    <?php } ?>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Настройки</a></li>
    
   
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="orders">
       <!--datatable-->

        <table id="table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Задача</th>
                        <th>Заказчик</th>
                        <th>Стоимость заказчика</th>
                        <th>Дата окончания</th>
                        <th>Статус</th>
                    </tr>
                </thead>    
                <tbody>
            <?php foreach($this->acceptedTasks as $task){?>
                    <tr>
                        <td><a href="<?= $this->baseUrl().'/performer/task/view/id/'.$task['id'] ?>"><?= $task['title'] ?></a></td>
                        <td><a href="<?= $this->baseUrl().'/performer/customer/view/id/'.$task['customer_id'] ?>"><?= $task['u_username'].' '.$task['u_surname'] ?></a></td>
                        <td><?= $task['customers_price'] ?></td>
                        <td><?= date('d.m.Y', $task['final_date']) ?></td>
                        <td>
                            <?php switch ($task['status']){ 
                                 case 'taken': 
                                echo 'В работе';
                                break;
                                ?>
                            <?php } ?>
                        </td>
                    </tr>

            <?php } ?>
         </tbody>
        </table>       
       
    </div>
    <div role="tabpanel" class="tab-pane" id="tasks">
        <div class="row">
       <?php if($this->orders){?>     
       <table id="tasksTable" class="table table-striped table-bordered table-responsive" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Название</th>
                <th>Дата создания</th>
                <th>Дата выполнения</th>
                <th>Статус</th>
                <th>Удалить</th>
            </tr>
        </thead>    

        <tbody>
            <?php foreach($this->orders as $task){?>
            <tr id="tr<?= $task['id'] ?>">
                <td><a href="<?= $this->baseUrl().'/performer/task/performers-view/id/'.$task['id']?>"><?= $task['title'] ?></a></td>
                <td><?=  date('H:i d-m-Y', $task['created_at'])?></td>
                <td><?= date('H:i d-m-Y', $task['final_date']) ?></td>
                <td>
                  <?php switch($task['status']){
                         case "non_taken":
                             echo 'ожидание';
                             break;
                         case "closed":
                             echo "закрыта";
                             break;
                  }
                  ?>
                </td>
                <td>
                    <?php if($task['status'] == 'non_taken' || $task['status'] == 'closed'){?>
                    <button onclick="removeTask(<?= $task['id'] ?>)">Удалить</button>
                    <img style="display: none" id="remPrel<?= $task['id'] ?>" src="<?= $this->baseUrl()?>/images/blue_preloader.gif" width="50">
                     <?php } ?>
                </td>
            </tr>
            <?php } ?>
         </tbody>
        </table>
       <?php }else{?> 
            <div class="col-sm-12">
            Вы пока не создали ни одной задачи
            </div>
       <?php }?>    
        </div>
    </div>
    <?php if($this->userPrepositions){?>  
        <div role="tabpanel" class="tab-pane" id="app">
       <table id="tasksTable" class="table table-striped table-bordered table-responsive" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Задача</th>
                <th>Заказчик</th>
            </tr>
        </thead>    

        <tbody>
            <?php foreach($this->userPrepositions as $prep){?>
            <tr >
                <td><a href="<?= $this->baseUrl().'/performer/task/view/id/'.$prep['t_id']?>"><?= $prep['t_title'] ?></a></td>
                <td><a href="<?= $this->baseUrl().'/performer/customer/view/id/'.$prep['t_customer_id'] ?>"><?= $prep['cust_surname'].' '.$prep['cust_username'] ?></td>
                
            </tr>
            <?php } ?>
         </tbody>
        </table>
        </div>
    <?php } ?>
    <div role="tabpanel" class="tab-pane" id="settings">
      <div role="tabpanel2">
              
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">

                  <li role="presentation" class="active" ><a href="#data" aria-controls="data" role="tab" data-toggle="tab">Данные</a></li>
                  <li role="presentation"><a href="#category" aria-controls="category" role="tab" data-toggle="tab">Категории</a></li>
   
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  
                  <div role="tabpanel2" class="tab-pane active" id="data">
                   
                    <?= $this->form ?>
                  </div>
                  <div role="tabpanel2" class="tab-pane" id="category">
                     <?php foreach($this->categories as $category){?>
                        <div class="col-lg-12">
                           <strong><?= $category['title'] ?></strong>
                        </div>
                        <?php if(!empty($category['children'])){?>
                           <div style="padding-left: 25px">
                             <?php foreach($category['children'] as $kid){?>
                               <div class="col-lg-12">
                                 
                                 <input type="checkbox" id="check<?= $kid['id'] ?>" name="category" <?php if($kid['user_id']){?> checked <?php } ?> onchange="changeCategory(<?= $kid['id'] ?>);" >
                                 <label for="category"><?= $kid['title'] ?></label>
                                 <img id="prel<?= $kid['id'] ?>" style="display:none" src="<?= $this->baseUrl() ?>/images/blue_preloader.gif" width="45">
                               </div>
                             <?php } ?>
                        <?php } ?>
                          </div>
             
                      <?php } ?> 
                    
                  </div>
                </div>

       </div>
    </div>
  </div>

</div>
        </div>
    </div>



<script>
$(document).ready(function(){

    $('#table').DataTable();

    $( "#bi" ).datepicker();
 

}); 

$(function () {
  $('[data-toggle="tooltip"]').tooltip();
}); 

function fillBalance(){
    $('#balanceButton').hide();
    $('#balancePrel').show();
 var userId = '<?= $this->user->id ?>'; 
 var sum = $('#sum').val();
    $.ajax({
      type: 'POST',
      url: '<?= $this->baseUrl.'/performer/balance/fill-ajax'; ?>',
      data: {
          sum: sum,
          userId: userId
      },
      success: function(data){
          $('#sum').val('');
          $('#balSpan').text(data);
          $('#balancePrel').hide();
          $('#balanceButton').show();
          
      }
    });
}

function changeCategory(catId){ 
    if($('#check'+catId).is(':checked')){
        $('#prel'+catId).show();
        $.ajax({
          type: 'POST',
          url: '<?= $this->baseUrl.'/performer/settings/add-user-category'; ?>',
          data: {catId: catId},
          success: function(){
              $('#prel'+catId).hide();
          }
        });  
    }else{
    $('#prel'+catId).show();
        $.ajax({
          type: 'POST',
          url: '<?= $this->baseUrl.'/performer/settings/remove-users-category'; ?>',
          data: {catId: catId},
          success: function(data){
              $('#prel'+catId).hide();
          }
        });
    }

}

function removeTask(id){
$('#remPrel'+id).show();
$.ajax({
  type: 'POST',
  url: '<?= $this->baseUrl.'/performer/task/remove-task/'; ?>',
  data: {id: id},
  success: function(response){
      $('#remPrel'+id).hide();
      $('#tr'+id).remove();
  }
});   
}
</script>    
