    <div class="row">
        <div class="breadcrumbDiv col-lg-12">
              <ul class="breadcrumb">
                  <li> <a href="<?= $this->baseUrl() ?>">Главная</a> </li>
                 <li class="active" >Условия использования</li>
              </ul>
        </div>

        <div class="col-sm-12" style="padding:25px;">
            <?= $this->terms['content'] ?>
        </div>
   

</div>