    <div class="row">
        <div class="breadcrumbDiv col-lg-12">
              <ul class="breadcrumb">
                  <li> <a href="<?= $this->baseUrl() ?>">Главная</a> </li>
                 <li class="active" >Как это работает</li>
              </ul>
        </div>

    <div class="col-sm-12">
        <?= $this->about['content'] ?>
    </div>
    <?php if($this->about['js_map']){?>
        <div class="col-sm-12">
            <?= $this->about['js_map'] ?>
        </div>
    <?php } ?>
</div>