<div class="container">
    <div class="col-sm-12">
        <h3>Выбор категорий</h3>
    </div>
    <?php foreach($this->categories as $category){?>
   <div class="col-lg-12">
      <strong><?= $category['title'] ?></strong>
   </div>
   <?php if(!empty($category['children'])){?>
      <div style="padding-left: 25px">
        <?php foreach($category['children'] as $kid){?>
          <div class="col-lg-12">

            <input type="checkbox" id="check<?= $kid['id'] ?>" name="category" <?php if($kid['user_id']){?> checked <?php } ?> onchange="changeCategory(<?= $kid['id'] ?>);" >
            <label for="category"><?= $kid['title'] ?></label>
            <img id="prel<?= $kid['id'] ?>" style="display:none" src="<?= $this->baseUrl() ?>/images/blue_preloader.gif" width="45">
          </div>
        <?php } ?>
   <?php } ?>
     </div>

 <?php } ?> 
    <div class="col-sm-12" style="padding-bottom: 10px">
        <label>Обо мне</label>
        <textarea name="about" id="about" width="100%" class="form-control"></textarea>
    </div>
    <div class="col-sm-12">
        <button class="btn btn-primary" id="custCatButton">Отправить заявку</button>
        <img src="<?= $this->baseUrl().'/images/blue_preloader.gif' ?>" widht="50" style="display: none">
    </div>
</div>
<script>
    $(document).ready(function(){
        $('#custCatButton').bind("click", function(){
            applyPerformer();
        });
    });
function changeCategory(catId){ 
    if($('#check'+catId).is(':checked')){
        $('#prel'+catId).show();
        $.ajax({
          type: 'POST',
          url: '<?= $this->baseUrl.'/customer/office/add-user-category'; ?>',
          data: {catId: catId},
          success: function(){
              $('#prel'+catId).hide();
          }
        });  
    }else{
    $('#prel'+catId).show();
        $.ajax({
          type: 'POST',
          url: '<?= $this->baseUrl.'/customer/office/remove-users-category'; ?>',
          data: {catId: catId},
          success: function(data){
              $('#prel'+catId).hide();
          }
        });
    }

}

function applyPerformer(){
    var about = $('#about').val();
    var url  = '/customer/performers/request-to-be-performer/';
    console.log(url);
    if(confirm('Отправить заявку?')){
        $.ajax({
          type: 'POST',
          url: '/customer/performers/request-to-be-performer/',
          data: {id: 'id', about: about},
          success: function(){
              alert('Ваша заявка отправлена администратору.');
              $('#sendApp').remove(500);
              var url = '<?= $this->baseUrl().'/customer/office/' ?>';
              window.location.href = url;
          }
        });
    }
}
</script>