  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>  
  <!-- if phone is not verified -->
<div class="modal signUpContent fade" id="ModalSmsCode" tabindex="-1" role="dialog" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
        <h3 class="modal-title-site text-center" > SMS код </h3>
      </div>
      <div class="modal-body">
          <p>
             Для подтверждения вашего номера введите код полученный в SMS
          </p>
          <input type="text" id="smsCode"><p class="text-danger" id="modalCodeError" style="display: none">Неверный код</p></br>
          <img id="smsModalPreloader" style="display: none" src="<?= $this->baseUrl().'/images/blue_preloader.gif' ?>" width="50"></br>
          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Закрыть</button>
        <button id="takeCode" class="btn btn-primary" disabled >Подтвердить</button>
      </div>
    </div>
    <!-- /.modal-content --> 
    
  </div>
  </div>
    <div class="row">
        <div class="breadcrumbDiv col-lg-12">
              <ul class="breadcrumb">
                  <li> <a href="<?= $this->baseUrl() ?>">Главная</a> </li>
                 <li class="active" >Личный кабинет</li>
              </ul>
        </div>
    </div>
    <div class="row transitionfx">
  
   <!-- left column -->
    <div class="col-lg-4 col-md-4 col-sm-4">
    	<!-- product Image and Zoom -->

    <div class="main-image sp-wrap col-lg-12 no-padding style3" style="display: inline-block;"> 
         
        
         
    <div class="sp-large" style="left: 0px; top: 0px;">
            <img width="100%" src="<?= $this->baseUrl() ?>/images/users_images/<?= $this->user['image'] ?>" class="img-responsive" alt="img" />

    </div>
    </div>
        <div class="col-sm-8" style="text-align: center">
            <a style="text-decoration: underline" onclick="$('#imageInput').click();return false;">Сменить фото</a>
        </div>
    </div><!--/ left column end -->
    <form   enctype="multipart/form-data" id="avatarForm" method="post" action="/customer/office/change-avatar">
        <input type="hidden" name="userId" value="<?= $this->user['id'] ?>">
        <input type="file" style="display:none" id="imageInput" name="image">
    </form>
    
    <!-- right column -->
    <div class="col-lg-8 col-md-8 col-sm-8">
    <div class="col-sm-8">
      <h1 class="product-title"><?= $this->user['username']." ".$this->user['surname']?></h1>
    </div>
    <div class="col-sm-4">
      <?php if($this->closedTasks){ ?>
      
        <ul class="swatches Color">
          <?php switch ($this->rating){
              case 1:?>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <?php break;
              case 2:
      ?>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
        <?php
        break;
        case 3: ?>  
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
        <?php break;
              case 4:
    ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <?php break;
              case 5:
    ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
             <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
          <?php 
          break;
          default: ?>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <?php }?>
        </ul>
      
      <?php } ?>
    </div>
    <div class="col-sm-12">
      <h3 class="product-code">Возраст : <?php $unixAge = time() - $this->user['birth_date'];
                $unixYears = $unixAge/31536000;
                $age = floor($unixYears);
                ?>
                <?= $age;  ?> лет
      </h3>
    </div>
    <div class="col-sm-12">
      <h3 class="product-code"> 
              Создано задач:  <?php $tasksAmount = count($this->customersTasks); ?>
              <?= $tasksAmount; ?> 
      </h3>
    </div>
<!--      <div class="color-details"> -->

     
      
      <div class="clear"></div>

     <div class="col-sm-12"> 
      <div style="clear:both"></div>
      <div class="product-share clearfix">
        <p> Привязка к соцсетям </p>
        <div class=""> 
            <?php if(!$this->user['fb']){?>
                <a href="<?= $this->baseUrl().'/social-attach/fb-link/' ?>" data-toggle="tooltip" data-placement="left" title="Нажмите для привязки своего аккаунта" >
                    <img width="30px" src="<?= $this->baseUrl().'/ico/fb_wb.png' ?>" >
                </a> 
            <?php }else{ ?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан" width="40px" src="<?= $this->baseUrl().'/ico/fb.png' ?>" >
            <?php } ?>
            <?php if(!$this->user['ok']){?>
                <a href="<?= $this->baseUrl().'/social-attach/ok-link/' ?>" data-toggle="tooltip" data-placement="left" title="Нажмите для привязки своего аккаунта">
                    <img width="30px" src="<?= $this->baseUrl().'/ico/ok_wb.png' ?>">
                </a> 
            <?php }else{ ?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан" width="40px" src="<?= $this->baseUrl().'/ico/ok.png' ?>" >
            <?php } ?>
            <?php if(!$this->user['vk']){?>
                <a href="<?= $this->baseUrl().'/social-attach/vk-link/' ?>"  data-toggle="tooltip" data-placement="left" title="Нажмите для привязки своего аккаунта">
                    <img width="30px" src="<?= $this->baseUrl().'/ico/vk_wb.png' ?>">
                </a>
            <?php }else{ ?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан"  width="40px" src="<?= $this->baseUrl().'/ico/vk.png' ?>" >
            <?php } ?>
        </div>
      </div>
      </div>
      
      <div class="product-share clearfix">
        <?php if(!$this->user['phonenumber']){?>
          <div class="row">
          <div class="col-sm-6">
            <div class="form-group " id="sendSmsForm">
               <label class="sr-only" for="phonenumber">Ваш контактный номер телефона</label>
               <label >Ваш контактный номер телефона</label></br>
               <div class="input-group">
                 <div class="input-group-addon">+375</div>
                 <input autocomplete="off" type="text" class="form-control" id="phonenumberInp" <?php if($this->user['phonenumber']){?>value="<?= mb_substr($this->user['phonenumber'], 3, 10,'utf-8')?>" <?php } ?>  placeholder="Введите ваш номер телефона...">
                 <div id="sendSmsButton" style="display: none; background-color:#4ec67f" class="input-group-addon btn">Получить код</div>
               </div>
               <img id="smsPreloader" style="display: none" src="<?= $this->baseUrl().'/images/blue_preloader.gif' ?>" width="50">
               <p class="text-danger" id="phoneErrorTaken" style="display: none">Номер занят</p>
               <p class="text-danger" id="phoneErrorInvalid" style="display: none">Неверный номер</p>
             </div>
             </div><div class="col-sm-3"></div>
             <div class="col-sm-3"></div>
                 
          </div>
             <div class="col-sm-3">
<!--                 <button style="display: none" class="btn btn-primary btn-xs"  id="enterCodeBut">Ввести код</button>-->
             </div>
        <?php }else{?>

            <?php if($this->user['phone_verified'] == 0){?>
                
                <?php if(!$this->user['pv_id']){?>
                     <div class="row">
                        <div class="col-sm-6">
                          <div class="form-group " id="sendSmsForm">
                             <label class="sr-only" for="phonenumber">Ваш контактный номер телефона</label>
                             <label >Ваш контактный номер телефона</label></br>
                             <div class="input-group">
                               <div class="input-group-addon">+375</div>
                               <input autocomplete="off" type="text" class="form-control" id="phonenumberInp" <?php if($this->user['phonenumber']){?>value="<?= mb_substr($this->user['phonenumber'], 3, 10,'utf-8')?>" <?php } ?> placeholder="Введите ваш номер телефона...">
                               <div id="sendSmsButton" style="display: none; background-color:#4ec67f" class="input-group-addon btn">Получить код</div>
                             </div>
                             <img id="smsPreloader" style="display: none" src="<?= $this->baseUrl().'/images/blue_preloader.gif' ?>" width="50">
                             <p class="text-danger" id="phoneErrorTaken" style="display: none">Номер занят</p>
                             <p class="text-danger" id="phoneErrorInvalid" style="display: none">Неверный номер</p>
                           </div>
                           </div><div class="col-sm-3"></div>
                           <div class="col-sm-3"></div>

                    </div>
                    <div class="col-sm-3">
<!--                        <button style="display: none" class="btn btn-primary btn-xs" id="enterCodeBut" >Ввести код</button>-->
                    </div>
                <?php }else{?>
                     <div class="row">
                        <div class="col-sm-6">
                          <div class="form-group " id="sendSmsForm">
                             <label class="sr-only" for="phonenumber">Ваш контактный номер телефона</label>
                             <label >Ваш контактный номер телефона</label></br>
                             <div class="input-group">
                               <div class="input-group-addon">+375</div>
                               <input autocomplete="off" type="text" class="form-control" id="phonenumberInp" <?php if($this->user['phonenumber']){?>value="<?= mb_substr($this->user['phonenumber'], 3, 10,'utf-8')?>" <?php } ?> placeholder="Введите ваш номер телефона...">
                               <div id="sendSmsButton" style="display: none; background-color:#4ec67f" class="input-group-addon btn">Получить код</div>
                             </div>
                             <img id="smsPreloader" style="display: none" src="<?= $this->baseUrl().'/images/blue_preloader.gif' ?>" width="50">
                             <p class="text-danger" id="phoneErrorTaken" style="display: none">Номер занят</p>
                             <p class="text-danger" id="phoneErrorInvalid" style="display: none">Неверный номер</p>
                           </div>
                           </div><div class="col-sm-3"></div>
                           <div class="col-sm-3"></div>

                    </div>
                    <div class="col-sm-3">
<!--                        <button style="display: none"  class="btn btn-primary btn-xs" id="enterCodeBut" >Ввести код</button>-->
                    </div>
                <?php }?>
            <?php }else{ ?>
                <img id="verificatePhone" data-toggle="tooltip" data-placement="left" title="Телефон верифицирован"  width="40px" src="<?= $this->baseUrl().'/ico/phone.png' ?>" >
                <a id="changePhoneLink">Сменить номер телефона</a>
                
                <div id="divChangePhone" style="display: none">
                    <div class="row">
                        <div class="col-sm-6">
                          <div class="form-group " id="sendSmsForm">
                             <label class="sr-only" for="phonenumber">Ваш контактный номер телефона</label>
                             <label >Ваш контактный номер телефона</label></br>
                             <div class="input-group">
                               <div class="input-group-addon">+375</div>
                               <input autocomplete="off" type="text" class="form-control" id="phonenumberInp" <?php if($this->user['phonenumber']){?>value="<?= mb_substr($this->user['phonenumber'], 3, 10,'utf-8')?>" <?php } ?> placeholder="Введите ваш номер телефона...">
                               <div id="sendSmsButton" style="display: none; background-color:#4ec67f" class="input-group-addon btn">Получить код</div>
                             </div>
                             <img id="smsPreloader" style="display: none" src="<?= $this->baseUrl().'/images/blue_preloader.gif' ?>" width="50">
                             <p class="text-danger" id="phoneErrorTaken" style="display: none">Номер занят</p>
                             <p class="text-danger" id="phoneErrorInvalid" style="display: none">Неверный номер</p>
                           </div>
                           </div><div class="col-sm-3"></div>
                           <div class="col-sm-3"></div>

                    </div>
                    <div class="col-sm-3">
<!--                        <button style="display: none" class="btn btn-primary btn-xs" id="enterCodeBut" >Ввести код</button>-->
                    </div>
                </div>
            <?php } ?>
        
        <?php } ?>
              </div>  
      </div>
      
    </div><!--/ right column end -->

<!--  </div>-->
    <div class="row">
        <div calss="col-lg-12" style="padding-bottom: 5px">
<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#orders" aria-controls="orders" role="tab" data-toggle="tab">Заказы</a></li>
    
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Профиль</a></li>
   
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="orders">
        <div class="row">
       <table id="tasksTable" class="table table-striped table-bordered table-responsive" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Название</th>
                <th>Дата создания</th>
                <th>Дата выполнения</th>
                <th>Статус</th>
                <th>Удалить</th>
            </tr>
        </thead>    

        <tbody>
            <?php foreach($this->customersTasks as $task){?>
            <tr id="tr<?= $task['id'] ?>">
                <?php  $tpObj = new Customer_Model_DbTable_TaskPrepositionModel();
                       $prepositions = count($tpObj->getTasksPrepositionis($task['id']));
                ?>
                <td>
                    <a href="<?= $this->baseUrl().'/customer/task/view/id/'.$task['id']?>">
                        <?= $task['title'] ?>
                    </a>
                    <?php if($task['status']== 'non_taken'){?>
                    
                        <?php if($prepositions > 0){?>
                            <span class="badge">
                               <?= $prepositions ?>
                           </span>
                        <?php } ?>
                    
                    <?php } ?>
                </td>
                <td><?=  date('Y-m-d H:i', $task['created_at'])?></td>
                <td><?= date('Y-m-d H:i', $task['final_date']) ?></td>
                <td>
                  <?php switch($task['status']){
                         case "non_taken":
                             echo 'ожидание';
                             break;
                         case "closed":
                             echo "закрыта";
                             break;
                         case "taken":
                             echo "в работе";
                             break;
                         default:
                             echo 'не известно';
                  }
                  ?>
                </td>
                <td>
                    <?php if($task['status'] == 'non_taken'){?>
                    <button onclick="removeTask(<?= $task['id'] ?>)">Удалить</button>
                    <img style="display: none" id="remPrel<?= $task['id'] ?>" src="<?= $this->baseUrl()?>/images/blue_preloader.gif" width="50">
                     <?php } ?>
                </td>
            </tr>
            <?php } ?>
         </tbody>
        </table>
        </div>
    </div>

    <div role="tabpanel" class="tab-pane" id="settings">
      <div role="tabpanel2">
         <?= $this->form ?>

       </div>
    </div>
  </div>

</div> 
        </div>
    </div>

<!--------------------------->
<?php if(!$this->user['phonenumber']){

    $this->user['phonenumber'] = 0;
}
?>
<script>
$(document).ready(function(){ 
    
   $('#changePhoneLink').bind('click', function(){
       
       $('#verificatePhone').toggle();
       $('#divChangePhone').toggle();
   }); 
   
 
    
   $('#enterCodeBut').bind("click",function(){
       $('#smsModalPreloader').hide();
       $('#modalCodeError').hide();
       $('#smsCode').val('');
       $('#ModalSmsCode').modal('show');
   });
       $('#smsCode').bind('keyup', function(){
        var codeLng = $('#smsCode').val().length;
        if(codeLng == 6){
            $('#takeCode').removeAttr("disabled");
        }
    });
    
    $('#takeCode').bind('click', function(){
        var code = $('#smsCode').val();
        $('#smsModalPreloader').show();
        verifyPhone(code);
    });    
    
    $('#tasksTable').DataTable({
    });
    var phonenumber = $('#phonenumberInp').val();
    var numberLng = phonenumber.length;
    if(numberLng == 9){
        $('#sendSmsButton').show();
        $('#enterCodeBut').show();
    }else{
        $('#sendSmsButton').hide();
        $('#enterCodeBut').hide();
    }
    $('#phonenumberInp').bind("keyup", function(){
        var phonenumber = $('#phonenumberInp').val();
        var numberLng = phonenumber.length;
        if(numberLng == 9){
//           checkPhoneForUniq(phonenumber);
            $('#sendSmsButton').show();
            $('#enterCodeBut').show();
    
        }else{
            $('#sendSmsButton').hide();
            $('#enterCodeBut').hide();
        }
    });
    
    $('#smsModalPreloader').bind('click', function(){
        
    });
//setTimeout(function() {
//      $('#smsAgain').removeAttr("disabled");
//}, 60000);  

$('#smsAgain').bind("click", function(){
    $(this).hide();
    $('#activatePrel').show();
    var phoneVal = $('#phonenumberInp').val();
    editUser(phoneVal, <?= $this->user['id'] ?>);
    sendSms('375'+phoneVal, <?= $this->user['id'] ?>);
    
});

$('#imageInput').change(function(){
   $('#avatarForm').submit();
});

$('#sendSmsButton').bind('click', function(){  

        $('#sendSmsButton').hide();
        $('#smsPreloader').show();
        var phoneVal = $('#phonenumberInp').val();
        editUser(phoneVal, <?= $this->user['id'] ?>);
        sendSms('375'+phoneVal, <?= $this->user['id'] ?>);

});

    $('#activation').bind("click", function(e){
        e.preventDefault();
        var code = $('#code').val();
        
        if(code == ''){
            $('#codeError').show();
        }
        if(code != ''){
            activatePhone( code);
        }
    $('#code').keyup(function(e){
     if(e.keyCode == 13)
     {
         activatePhone(code);
     }
    });     
        
    });

$('#email_input').bind("keyup",function(){
    
    var emailVal = $('#email_input').val();
    if(emailVal.indexOf('@') != -1){
       // check if email taken
        $.ajax({
                type: 'POST',
                url: '<?= $this->baseUrl.'/user/check-email-for-unique'; ?>',
                data: {emailVal: emailVal},
                success: function(data){$('#email_input').after('<p id="emailUnqErr" style="display:none" class="text-danger">Введенный email занят</p>');
                    if(data === 'taken'){
                        $('#emailUnqErr').show();
                    }else if(data === 'free'){
                        $('p#emailUnqErr').hide();
                    }
              }
            });
    }
});
});

function verifyPhone(code){
    $.ajax({
        type: 'POST',
        url: '<?= $this->baseUrl.'/phone-activation/activate-account'; ?>',
        data: {code: code},
        success: function(data){
           data = JSON.parse(data);
           if(data.code == 'false'){
               $('#smsModalPreloader').hide();
               $('#modalCodeError').show();
           }else if(data.code == '1'){
                $.ajax({
                        type: 'POST',
                        url: '<?= $this->baseUrl.'/phone-activation/activate'; ?>',
                        data: {code: code},
                        success: function(data){
                            location.reload();
                         }
                     });
           }
         }
     });
}

function editUser(phoneNumber, userId){

    $.ajax({
        type: 'POST',
        url: '<?= $this->baseUrl.'/registration/edit-user'; ?>',
        data: {phoneNumber: phoneNumber, userId: userId},
        success: function(data){console.log(phoneNumber);
            if(data === 'true'){

            }
            
         }
     });
     }
function activatePhone(code){
$('#codeError').hide();
$('#phoneVerificationError').hide();
$('#activation').hide();  
$('#activatePrel').show();
$.ajax({
    type: 'POST',
    url: '<?= $this->baseUrl.'/phone-activation/activate-account'; ?>',
    data: { code: code},
    success: function(data){
        data = JSON.parse(data);
        if(data.code != '1'){
                  $('#codeError').show();
                   
               
                $('#activation').show();  
                $('#activatePrel').hide();
        }else{
        // the ajax activates user account console.log(data);
            $.ajax({
                type: 'POST',
                url: '<?= $this->baseUrl.'/registration/activate-account-by-phone'; ?>',
                data: {userId: data.user_id},
                success: function(data){
                    location.reload();
              }
            });
        }
        }
});
}

$(function () {
  $('[data-toggle="tooltip"]').tooltip();
});

function sendSms(phoneNumber, userId){
    $.ajax({
        type: 'POST',
        url: '<?= $this->baseUrl.'/sms/phone-verify'; ?>',
        data: {phoneNumber: phoneNumber, userId: userId},
        success: function(data){
            if(data == 'true'){
                $('#ModalSmsCode').modal('show');
                $('#smsPreloader').hide();
//                setTimeout(function() {
                    $('#sendSmsButton').show();
//                }, 60000);
            }else if(data == -4){
                $('#smsPreloader').hide();
                $('#phoneErrorInvalid').show();
                $('#phoneErrorInvalid').fadeOut(3000);
                $('#sendSmsButton').show();
            }else if(data == -10){
                $('#smsPreloader').hide();
                $('#phoneError').show();
                $('#phoneError').fadeOut(1000);
                $('#sendSmsButton').show();
            }
            
         }
     });
     }

function removeTask(id){
$('#remPrel'+id).show();
$.ajax({
  type: 'POST',
  url: '<?= $this->baseUrl.'/customer/task/remove-task/'; ?>',
  data: {id: id},
  success: function(response){
      $('#remPrel'+id).hide();
      $('#tr'+id).remove();
  }
});   
}
</script>
