  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>                  
    <div class="row">
        <div class="breadcrumbDiv col-lg-12">
              <ul class="breadcrumb">
                  <li> <a href="<?= $this->baseUrl() ?>">Главная</a> </li>
                 <li class="active" >Личный кабинет</li>
              </ul>
        </div>
    </div>
    <div class="row transitionfx">
  
   <!-- left column -->
    <div class="col-lg-6 col-md-6 col-sm-6">
    	<!-- product Image and Zoom -->

    <div class="main-image sp-wrap col-lg-12 no-padding style2 style2look2" style="display: inline-block;"> 
         
        
         
    <div class="sp-large" style="left: 0px; top: 0px;">
            <img width="100%" src="<?= $this->baseUrl() ?>/images/users_images/<?= $this->user['image'] ?>" class="img-responsive" alt="img" />

    </div>
    </div>
    </div><!--/ left column end -->
    
    
    <!-- right column -->
    <div class="col-lg-6 col-md-6 col-sm-5">
    
      <h1 class="product-title"><?= $this->user['username']." ".$this->user['surname']?></h1>
      <h3 class="product-code">Возраст : <?php $unixAge = time() - $this->user['birth_date'];
                $unixYears = $unixAge/31536000;
                $age = floor($unixYears);
                ?>
                <?= $age;  ?> лет
      </h3>
      <div class="product-price"> 
          <span class="price-sales">
              Создано задач:  <?php $tasksAmount = count($this->customersTasks); ?>
              <?= $tasksAmount; ?>
          </span>  
      </div>
<!--      <div class="color-details"> -->

      <?php if($this->closedTasks){ ?>
      <div class="color-details"> <span class="selected-color"><strong>Рейтинг</strong></span>
        <ul class="swatches Color">
          <?php switch ($this->rating){
              case 1:?>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <?php break;
              case 2:
      ?>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
        <?php
        break;
        case 3: ?>  
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
        <?php break;
              case 4:
    ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <?php break;
              case 5:
    ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
             <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
          <?php 
          break;
          default: ?>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <?php }?>
        </ul>
      </div>
      <?php } ?>
      
      <div class="clear"></div>

      
      <div style="clear:both"></div>
      <div class="product-share clearfix">
        <p> Привязка к соцсетям </p>
        <div class=""> 
            <?php if(!$this->user['fb']){?>
                <a href="<?= $this->baseUrl().'/social-attach/fb-link/' ?>" data-toggle="tooltip" data-placement="left" title="Нажмите для привязки своего аккаунта" >
                    <img width="30px" src="<?= $this->baseUrl().'/ico/fb_wb.png' ?>" >
                </a> 
            <?php }else{ ?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан" width="40px" src="<?= $this->baseUrl().'/ico/fb.png' ?>" >
            <?php } ?>
            <?php if(!$this->user['ok']){?>
                <a href="<?= $this->baseUrl().'/social-attach/ok-link/' ?>" data-toggle="tooltip" data-placement="left" title="Нажмите для привязки своего аккаунта">
                    <img width="30px" src="<?= $this->baseUrl().'/ico/ok_wb.png' ?>">
                </a> 
            <?php }else{ ?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан" width="40px" src="<?= $this->baseUrl().'/ico/ok.png' ?>" >
            <?php } ?>
            <?php if(!$this->user['vk']){?>
                <a href="<?= $this->baseUrl().'/social-attach/vk-link/' ?>"  data-toggle="tooltip" data-placement="left" title="Нажмите для привязки своего аккаунта">
                    <img width="30px" src="<?= $this->baseUrl().'/ico/vk_wb.png' ?>">
                </a>
            <?php }else{ ?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан"  width="40px" src="<?= $this->baseUrl().'/ico/vk.png' ?>" >
            <?php } ?>
        </div>
      </div>
      <div class="product-share clearfix">
        <?php if(!$this->user['phonenumber']){?>
                  <p class="text-danger">Введите свой номер телефона в настройках аккаунта</p>
        <?php }else{?>
        <p> Верификация телефона </p>
        <img id="verificatePhone" style="display:none" data-toggle="tooltip" data-placement="left" title="Телефон верифецирован"  width="40px" src="<?= $this->baseUrl().'/ico/phone.png' ?>" >
        <div id="verifDiv" > 
            <?php if($this->user['phone_verified'] == 0){?>
                
                <?php if(!$this->user['pv_id']){?>
            <a id="verificatePhoneNum">
                    <img id="phoneVerifImg" data-toggle="tooltip" data-placement="left" title="Нажмите для верификации телефона"  width="30px" src="<?= $this->baseUrl().'/ico/phone_wb.png' ?>" >
                    </a>
                    <img id="phoneVerifyPreloader" width="50" src="<?= $this->baseUrl().'/images/blue_preloader.gif' ?>" style="display: none">
                    <p id="smsNumError" class="text-danger" style="display:none">Неправильный формат номера телефона</p>
                    <p id="smsUnavError" class="text-danger" style="display:none">Сервис временно не работает</p>
                    <div  id="verificateDiv" style="display: none">

                    </div>
                <?php }else{?>
                     
                        <div  id="verificateDiv">
                        <div class="form-inline">

                          <div class="form-group" style="padding-bottom: 15px">
                            <p id="codeError" style="display: none" class="text-danger">Неверный код</p>
                            <div class="input-group">
                              <input type="text" class="form-control" id="code" placeholder="SMS-код">

                            </div>
                          </div>
                </br>

                        <div style="padding-top: 10px">
                            <a class="btn btn-primary" id="activation">Активация</a>
                            <img id="activatePrel" src="<?= $this->baseUrl().'/images/blue_preloader.gif' ?>" width="60" style="display: none">
                          
<!--                            </form>-->

                          </div>
                </div>
                          </div>
                <?php }?>
            <?php }else{ ?>
                <img id="verificatePhone" data-toggle="tooltip" data-placement="left" title="Телефон верифецирован"  width="40px" src="<?= $this->baseUrl().'/ico/phone.png' ?>" >
            <?php } ?>
        </div>
        <?php } ?>
      </div>
      
    </div><!--/ right column end -->

  </div>
    <div class="row">
        <div calss="col-lg-12" style="padding-bottom: 5px">
<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#orders" aria-controls="orders" role="tab" data-toggle="tab">Заказы</a></li>
    
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Настройки</a></li>
   
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="orders">
        <div class="row">
       <table id="tasksTable" class="table table-striped table-bordered table-responsive" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Название</th>
                <th>Дата создания</th>
                <th>Дата выполнения</th>
                <th>Статус</th>
                <th>Удалить</th>
            </tr>
        </thead>    

        <tbody>
            <?php foreach($this->customersTasks as $task){?>
            <tr id="tr<?= $task['id'] ?>">
                <?php  $tpObj = new Customer_Model_DbTable_TaskPrepositionModel();
                       $prepositions = count($tpObj->getTasksPrepositionis($task['id']));
                ?>
                <td>
                    <a href="<?= $this->baseUrl().'/customer/task/view/id/'.$task['id']?>">
                        <?= $task['title'] ?>
                    </a>
                    <?php if($task['status']== 'non_taken'){?>
                    
                        <?php if($prepositions > 0){?>
                            <span class="badge">
                               <?= $prepositions ?>
                           </span>
                        <?php } ?>
                    
                    <?php } ?>
                </td>
                <td><?=  date('H:i d-m-Y', $task['created_at'])?></td>
                <td><?= date('H:i d-m-Y', $task['final_date']) ?></td>
                <td>
                  <?php switch($task['status']){
                         case "non_taken":
                             echo 'ожидание';
                             break;
                         case "closed":
                             echo "закрыта";
                             break;
                         case "taken":
                             echo "в работе";
                             break;
                         default:
                             echo 'не известно';
                  }
                  ?>
                </td>
                <td>
                    <?php if($task['status'] == 'non_taken' || $task['status'] == 'closed'){?>
                    <button onclick="removeTask(<?= $task['id'] ?>)">Удалить</button>
                    <img style="display: none" id="remPrel<?= $task['id'] ?>" src="<?= $this->baseUrl()?>/images/blue_preloader.gif" width="50">
                     <?php } ?>
                </td>
            </tr>
            <?php } ?>
         </tbody>
        </table>
        </div>
    </div>

    <div role="tabpanel" class="tab-pane" id="settings">
      <div role="tabpanel2">
         <?= $this->form ?>

       </div>
    </div>
  </div>

</div> 
        </div>
    </div>

<!--------------------------->

<script>
$(document).ready(function(){ 
    $('#tasksTable').DataTable({
    });


    $('#verificatePhoneNum').bind('click', function(){  
        
            $('#verificatePhoneNum').hide();
            $('#phoneVerifyPreloader').show();
            sendSms(<?= $this->user['phonenumber'] ?>, <?= $this->user['id'] ?>);
            
    });

    $('#activation').bind("click", function(e){
        e.preventDefault();
        var code = $('#code').val();
        
        if(code == ''){
            $('#codeError').show();
        }
        if(code != ''){
            activatePhone( code);
        }
    $('#code').keyup(function(e){
     if(e.keyCode == 13)
     {
         activatePhone(code);
     }
    });     
        
    });

$('#email_input').bind("keyup",function(){
    
    var emailVal = $('#email_input').val();
    if(emailVal.indexOf('@') != -1){
       // check if email taken
        $.ajax({
                type: 'POST',
                url: '<?= $this->baseUrl.'/user/check-email-for-unique'; ?>',
                data: {emailVal: emailVal},
                success: function(data){$('#email_input').after('<p id="emailUnqErr" style="display:none" class="text-danger">Введенный email занят</p>');
                    if(data === 'taken'){
                        $('#emailUnqErr').show();
                    }else if(data === 'free'){
                        $('p#emailUnqErr').hide();
                    }
              }
            });
    }
});
});

function activatePhone(code){
$('#codeError').hide();
$('#phoneVerificationError').hide();
$('#activation').hide();  
$('#activatePrel').show();
$.ajax({
    type: 'POST',
    url: '<?= $this->baseUrl.'/phone-activation/activate-account'; ?>',
    data: { code: code},
    success: function(data){
        data = JSON.parse(data);
        if(data.code != '1'){
                  $('#codeError').show();
                   
               
                $('#activation').show();  
                $('#activatePrel').hide();
        }else{
        // the ajax activates user account console.log(data);
            $.ajax({
                type: 'POST',
                url: '<?= $this->baseUrl.'/registration/activate-account-by-phone'; ?>',
                data: {userId: data.user_id},
                success: function(data){
                    location.reload();
              }
            });
        }
        }
});
}

$(function () {
  $('[data-toggle="tooltip"]').tooltip();
});

function sendSms(phoneNumber, userId){
    $.ajax({
        type: 'POST',
        url: '<?= $this->baseUrl.'/sms/phone-verify'; ?>',
        data: {phoneNumber: phoneNumber, userId: userId},
        success: function(data){
            if(data === 'true'){
                location.reload();
            }else if(data == -4){
                $('#phoneVerifyPreloader').hide();
                $('#smsNumError').show();
                $('#smsNumError').fadeOut(1000);
                $('#verificatePhoneNum').show();
            }else if(data == -10){
                $('#phoneVerifyPreloader').hide();
                $('#smsUnavError').show();
                $('#smsUnavError').fadeOut(1000);
                $('#verificatePhoneNum').show();
            }
            
         }
     });
     }

function removeTask(id){
$('#remPrel'+id).show();
$.ajax({
  type: 'POST',
  url: '<?= $this->baseUrl.'/customer/task/remove-task/'; ?>',
  data: {id: id},
  success: function(response){
      $('#remPrel'+id).hide();
      $('#tr'+id).remove();
  }
});   
}
</script>
