
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
          <li> <a href="<?= $this->baseUrl().'/performer/' ?>">Главная</a> </li>
        <li> <a href="<?= $this->baseUrl().'/performer/user/' ?>">Личный кабинет</a> </li>
        <li class="active"> Оплата </li>
      </ul>
    </div>
  </div>
  <!--/.row-->
  
  <div class="row">
    <div class="col-lg-9 col-md-9 col-sm-7">
      <h1 class="section-title-inner">
          <span>
              <i class="glyphicon glyphicon-hand-right"></i>
              Оплата
          </span>
      </h1>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-5 rightSidebar">
      <h4 class="caps">
          <a href="<?= $this->baseUrl().'/performer/user/' ?>">
              <i class="fa fa-chevron-left"></i> 
              В личный кабинет 
          </a>
      </h4>
    </div>
  </div> <!--/.row-->
  
  <div class="row">
    <div class="col-lg-9 col-md-9 col-sm-12">
      <div class="row userInfo">
        <div class="col-xs-12 col-sm-12">
          <div class="w100 clearfix">
            <ul class="orderStep orderStepLook2">
              
              <li class="active"> <a> <i class="fa  fa-tachometer  "></i> <span> Ввод суммы </span></a></li>
              <li> <a><i class="fa  fa-check-square "> </i><span>Подтверждение</span> </a> </li>
              <li> <a><i class="fa fa-money "> </i><span>Оплата</span></a> </li>
            </ul>
            <!--/.orderStep end--> 
          </div>
          
          
          <div class="w100 clearfix">
            <div class="row userInfo">
              <div class="col-lg-12">
                <h2 class="block-title-2"> Введите необходимую сумму. </h2>
              </div>
              
              <form id="pointsForm" method="POST" action="<?= $this->baseUrl().'/performer/payment/index' ?>">

                <div class="col-xs-12 col-sm-6">
                  <div class="form-group " id="inputDiv">
                        <label>Введите сумму</label>
                        <input type="text" name="pointsQuantity" id="pointsQuantity" class="form-control" >
                        <p class="text-danger" id="priceError" style="display: none">
                            * Проверьте вводимые данные
                        </p>
                  </div>
                  
                  
                </div>
              </form>
            </div>
            <!--/row end--> 
            
          </div>
          <div class="cartFooter w100">
            <div class="box-footer">
              <div class="pull-left">
                  <a class="btn btn-primary" href="<?= $this->baseUrl().'/performer/user/' ?>"> 
                      <i class="fa fa-arrow-left"></i>
                      &nbsp; В личный кабинет 
                  </a> 
              </div>
              <div class="pull-right"> 
                  <a class="btn btn-primary btn-small " id="sbm" disabled >
                      Подтвердить &nbsp; 
                      <i class="fa fa-arrow-circle-right"></i>
                  </a>
              </div>
            </div>
          </div>
          <!--/ cartFooter --> 
          
        </div>
      </div>
      <!--/row end--> 
      
    </div>
    <div class="col-lg-3 col-md-3 col-sm-12 rightSidebar">
      <div class="w100 cartMiniTable">
        <table id="cart-summary" class="std table">
          <tbody>

            
            <tr>
              <td> Итоговая сумма </td>
              <td class=" site-color" id="total-price">0 </td>
            </tr>
          </tbody>
          <tbody>
          </tbody>
        </table>
      </div>
      <!--  /cartMiniTable--> 
      
    </div>
    <!--/rightSidebar--> 
    
  </div> <!--/row-->
  
  <div style="clear:both"></div>




<script>
$(document).ready(function(){
    $('#pointsQuantity').bind('keyup', function(){
        var quantity = $('#pointsQuantity').val();

        if(!isNaN(quantity)){
            $('#inputDiv').removeClass('has-error');
            $('#priceError').hide();
            $('#sbm').attr('disabled', false);
            var total = quantity;
            $('#totalSum').val(quantity);
            $('#total-price').text(quantity);
            $('#pointsAmount').text(quantity);
        }else{
            $('#totalSum').val(0);
            $('#total-price').text(0);
            $('#pointsAmount').text(0);
            $('#inputDiv').addClass('has-error');
            $('#priceError').show();
            $('#sbm').attr('disabled', true);
        }
    });
    
    $('#sbm').bind("click", function(){
        $('#pointsForm').submit();
    });
});
</script>