<script type="text/javascript" src="<?= $this->baseUrl() ?>/assets/js/jquery/1.8.3/jquery.js"></script> 
<div class="col-sm-4">
    <?php if($this->error){?>
     <p  class="text-danger"><?= $this->error ?></p>
    <?php }else{?>
     <form method="post" action="<?= $this->baseUrl()."/registration/pass-change/"?>">
         <input type="hidden" name="hash" value="<?= $this->hash ?>">
         <div class="form-group">
            <input id="pass" name="pass" type="password" class="form-control" id="email" placeholder="Пароль">
         </div>
         <div class="form-group">
            <input id="passConfRec" type="password" class="form-control" id="email" placeholder="Потверждение">
         </div>
         <p id="passError" class="text-danger" style="display: none">Пароли не совпадают</p>
         <button id="submitRec" style="display: none" class="btn  btn-block btn-primary">Изменить</button>
     </form>
    <?php }?> 
</div>
<script>
$(document).ready(function(){
    $('#passError').hide();
    $('#passConfRec').keyup(function(){
        checkPassRec();
    });
});
function checkPassRec(){
    var pass = $('#pass').val();
    var passConf = $('#passConf').val();
    if(pass == passConf){
        $('#passError').hide(); 
        $('#submitRec').show(); 
    }else{
        $('#passError').show(); 
        $('#submitRec').hide(); 
    }
}
</script>