<div class="col-sm-12">
    <?php if($this->error){?>
     <p  class="text-danger"><?= $this->error ?></p>
    <?php }else{?>
     <form method="post" action="<?= $this->baseUrl()."/registration/pass-change/"?>">
         <input type="hidden" name="hash" value="<?= $this->hash ?>">
         <div class="form-group">
            <input id="pass" name="pass" type="password" class="form-control" id="email" placeholder="Пароль">
         </div>
         <div class="form-group">
            <input id="passConf" type="password" class="form-control" id="email" placeholder="Потверждение">
         </div>
         <p id="passError" class="text-danger" style="display: none">Пароли не совпадают</p>
         <button id="submit" style="display: none" class="btn btn-default">Изменить</button>
     </form>
    <?php }?> 
</div>
<script>
$(document).ready(function(){
    $('#passError').hide();
    $('#passConf').keyup(function(){
        checkPass();
    });
});
function checkPass(){
    var pass = $('#pass').val();
    var passConf = $('#passConf').val();
    if(pass == passConf){
        $('#passError').hide(); 
        $('#submit').show(); 
    }else{
        $('#passError').show(); 
        $('#submit').hide(); 
    }
}
</script>