<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
                <h3>Контакты</h3>
            </div>
        <?php if($this->successMes){?>
            <div class="col-sm-12">
                <p class="text-success"><?= $this->successMes ?></p>
            </div>
        <?php }?>
        <form action="<?= $this->baseUrl().'/admin/settings/edit-contacts/' ?>" method="post">
            <div class="col-sm-12" style="padding-bottom: 10px">
                <label>Текст</label>
                <textarea name="content" id="content" ><?php if($this->contacts['content']):?><?= $this->contacts['content'] ?><?php endif;?></textarea>
            </div>
            <div class="col-sm-12" style="padding-bottom: 10px; width: 100%">
                <label>Код для карты</label>
                <textarea style=" width: 100%" name="js_map" ><?php if($this->contacts['js_map']):?><?= $this->contacts['js_map'] ?><?php endif;?></textarea>
            </div>
            <div class="col-sm-12" >
                <input type="submit" class="btn btn-primary" value="Изменить">
            </div>
        </form>
    </div>
</div>
        <script type="text/javascript">
             CKEDITOR.replace( 'content' );
        </script>