<table id="paymentTable" class="table table-striped table-bordered table-responsive" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>ID платежа</th>
                <th>Плательщик</th>
                <th>Сумма</th>
                <th>Дата</th>
                <th>Номер заказа</th>
                <th>ID транзакции</th>
                <th>Подпись</th>
            </tr>
        </thead>    
 

        <tbody>
        <?php foreach($this->payments as $payment){?>
            <tr>
                <td>
                    <?= $payment['order_id'] ?>
                </td>
                <td>
                    <a href="<?= $this->baseUrl().'/admin/performers/view/id/'.$payment['user_id'].'/' ?>">
                        <?= $payment['u_username']." ".$payment['u_surname'] ?>
                    </a>
                </td>
                <td>
                    <?= $payment['amount'] ?>
                </td>
                <td>
                    <?= date("d.m.y H:i",$payment['time']) ?>
                </td>
                <td>
                    <?= $payment['order_num'] ?>
                </td>
                <td>
                    <?= $payment['transaction_id'] ?>
                </td>
                <td>
                    <?= $payment['wsb_signature'] ?>
                </td>
            </tr>
        <?php } ?>            
        </tbody>
        
</table>     
<script>
    $(document).ready(function(){
        $('#paymentTable').DataTable();
    });
</script>