
  <link href="<?= $this->baseUrl().'/cropper/css/' ?>cropper.css" rel="stylesheet">
  <link href="<?= $this->baseUrl().'/cropper/css/' ?>cropper-main.css" rel="stylesheet"><?php if($this->performer['role'] == 'performer'){?>
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
          <li> <a href="<?= $this->baseUrl().'/customer/' ?>">Главная</a> </li>
          <li> <a href="<?= $this->baseUrl().'/customer/performers/' ?>">Список исполнителей</a> </li>
        <li class="active"><?= $this->performer['username'].' '.mb_substr($this->performer['surname'], 0, 1, 'utf-8').'.' ?> </li>
      </ul>
    </div>
  </div>

  <div class="row transitionfx"> 
    
    <!-- left column -->
    <div class="col-lg-3 col-md-3 col-sm-3"> 
      <!-- product Image and Zoom -->
      
      <div class="main-image sp-wrap col-lg-12 no-padding style3" style="display: inline-block;">
          <div class="sp-large avatar-view"  style="left: 0px; top: 0px;">
              
                  <img width="100%" src="<?= $this->baseUrl().'/images/users_images/'.$this->performer['image'] ?>" class="img-responsive" alt="img">
              
          </div>
      </div>
    </div>
    <!--/ left column end --> 
    
    <!-- right column -->
    <div class="col-lg-9 col-md-9 col-sm-9">
        <div class="col-sm-8">
      <h1 class="product-title"><?= $this->performer['username'].' '.mb_substr($this->performer['surname'], 0, 1, 'utf-8').'.' ?></h1>
      <?php $sec = time()-$this->performer['birth_date'];
            $age = $sec/31556926;
            $age = floor($age);
      ?>
      </div>
        <div class="col-sm-4">
            <?php if($this->closedTasks){ ?>
      
                <ul class="swatches Color">
          <?php switch ($this->rating){
              case 1:?>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
          <?php break;
              case 2:
      ?>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
        <?php
        break;
        case 3: ?>  
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
        <?php break;
              case 4:
    ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
          <?php break;
              case 5:
    ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
            <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
             <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
          <?php 
          break;
          default: ?>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
          <?php }?>
        </ul>
      
      <?php } ?>
        </div>
        <div class="col-sm-12">
      <h3 class="product-code">Возраст : <?= $age; ?> лет</h3>
      </div>
          <div class="col-sm-12"> 
          <h3 class="product-code">
              Создано задач:  <?php $customersTasksAmount = count($this->customersTasks); ?>
              <?= $customersTasksAmount; ?>
          </h3>  
      </div>
      
      <div class=" col-sm-12"> 
          <h3 class="product-code">
                <?php
                if($this->closedTasks){
                   $closedTasksAmount = count($this->closedTasks);

                ?>
                <?php if($closedTasksAmount){ ?>
                     Выполненных работ: <?= $closedTasksAmount ?>
                <?php }else{ ?>
                     Пользователь еще не завершил ни одного задания
                <?php } 
                } ?>
          </h3>  
      </div>

      <div class="details-description col-sm-12">
          <h3 class="product-code">Сферы деятельности :</h3>
          
              <?php foreach($this->usersCategories as $cat){?>
                <small><?= $cat['mc_title'].'.  '; ?></small>
              <?php } ?>
          
      </div>
      
      
      <!--/.color-details-->

      
      <div class="clear"></div>

      <!--/.product-tab-->
      
      <div style="clear:both"></div>
      <?php if($this->performer['vk'] || $this->performer['ok'] || $this->performer['fb']){?>
      <div class="product-share clearfix col-sm-12">
        <p> Привязка к соцсетям </p>
        <div class="socialIcon">
            <?php if($this->performer['vk']){?>
                <img src="<?= $this->baseUrl().'/ico/vk.png' ?>" height="50px">
            <?php } if($this->performer['ok']){?>
                <img src="<?= $this->baseUrl().'/ico/ok.png' ?>" height="50px">
            <?php } if($this->performer['fb']){?>
                <img src="<?= $this->baseUrl().'/ico/fb.png' ?>" height="50px">
            <?php }?>
        </div>
      </div>
      <?php } ?>
      <!--/.product-share--> 
      
    </div>
    <?php if($this->performer['about']){?>
        <div class="col-lg-12" style="padding-bottom: 10px">
            <h3 class="block-title-3">
                    Дополнительная информация  
            </h3>
            <p><?= $this->performer['about'] ?></p>
        </div>
    <?php } ?>
    <!--/ right column end --> 
    <?php if($this->feedbacks->count() > 0){?>
        <div class="col-lg-12" style="padding-bottom: 10px">
            <h3 class="block-title-3">
                Отзывы  
                <span style="padding-left: 30px;">
                    <?= $this->positiveAmount ?> 
                    <img src="<?= $this->baseUrl().'/images/like.png' ?>" width="25">
                </span>    
                <span style="padding-left: 30px;">
                    <?= $this->negativeAmount ?> 
                    <img src="<?= $this->baseUrl().'/images/dislike.png' ?>" width="25">
                </span>    
            </h3>
            <div class="row block-title-3">
            <div class="col-sm-3">
                <h3 class="product-code">
                    Средняя оценка  : 
                </h3> 
            
                <ul class="swatches Color">
                        <?php switch ($this->rating){
                            case 1:?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php break;
                            case 2:
                    ?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                      <?php
                      break;
                      case 3: ?>  
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                      <?php break;
                            case 4:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php break;
                            case 5:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                           <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                        <?php 
                        break;
                        default: ?>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php }?>
                      </ul>

                    <?php } ?>
                </div>
                <div class="col-sm-2">
                    <h4 class="">
                        Качество: 
                        <ul class="swatches Color">
                        <?php switch ($this->mainRating['quality']){
                            case 1:?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php break;
                            case 2:
                    ?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                      <?php
                      break;
                      case 3: ?>  
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                      <?php break;
                            case 4:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php break;
                            case 5:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                           <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                        <?php 
                        break;
                        default: ?>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php }?>
                      </ul>
                    </h4>
                </div>
                <div class="col-sm-2">
                    <h4 class="">
                        Пунктуальность: 
                        <ul class="swatches Color">
                        <?php switch ($this->mainRating['punctuality']){
                            case 1:?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php break;
                            case 2:
                    ?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                      <?php
                      break;
                      case 3: ?>  
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                      <?php break;
                            case 4:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php break;
                            case 5:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                           <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                        <?php 
                        break;
                        default: ?>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php }?>
                      </ul>
                    </h4>
                </div>
                <div class="col-sm-2">
                    <h4 class="">
                        Вежливость: 
                        <ul class="swatches Color">
                        <?php switch ($this->mainRating['politeness']){
                            case 1:?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php break;
                            case 2:
                    ?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                      <?php
                      break;
                      case 3: ?>  
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                      <?php break;
                            case 4:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php break;
                            case 5:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                           <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="20"> </li>
                        <?php 
                        break;
                        default: ?>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="20"> </li>
                        <?php }?>
                      </ul>
                    </h4>
                </div>
                </div>
                    
            <?php foreach($this->feedbacks as $feedback){?>
            <div class="row block-title-custom">
                <div class="col-sm-1 col-xs-3">
                    <img class="img-thumbnail" width="100%" src="<?= $this->baseUrl().'/images/users_images/'.$feedback['u_image'] ?>">
                </div>    
                <div class="col-sm-11 col-xs-9">
                    <b><?= $feedback['u_username'].' '.mb_substr($feedback['u_surname'],0,1,'utf-8').'.' ?></b>
                    <small style="color: #c9c1c1">
                    <?php if($feedback['user_from'] == $feedback['t_customer_id']){?>
                        (заказчик)
                    <?php }else if($feedback['user_from'] == $feedback['t_performer_id']){?>
                        (исполнитель)
                    <?php } ?>    
                    </small></br>
                    <small>
                        Отзыв о выполнении задания <a style="color: #1dd0fd" href="<?= $this->baseUrl().'/customer/task/view/id/'.$feedback['t_id'] ?>">"<?= $feedback['t_title'] ?>"</a>
                    </small>
                    <?php if($feedback['kind'] == 'positive'){?>
                        <img style="padding-left: 5px" src="<?= $this->baseUrl().'/images/like.png' ?>" width="20">
                    <?php }else if($feedback['kind'] == 'negative'){ ?>
                        <img style="padding-left: 5px" src="<?= $this->baseUrl().'/images/dislike.png' ?>" width="20">
                    <?php } ?> 
                    <p>
                        <?= $feedback['text'] ?>
                    </p>
                    <small class="col-sm-2">
                        Качество: 
                        <ul class="swatches Color">
                        <?php switch ($feedback['quality']){
                            case 1:?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <?php break;
                            case 2:
                    ?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                      <?php
                      break;
                      case 3: ?>  
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                      <?php break;
                            case 4:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <?php break;
                            case 5:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                           <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                        <?php 
                        break;
                        default: ?>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <?php }?>
                      </ul>
                    </small>
                    <small class="col-sm-2">
                        Пунктуальность: 
                        <ul class="swatches Color">
                        <?php switch ($feedback['punctuality']){
                            case 1:?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <?php break;
                            case 2:
                    ?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                      <?php
                      break;
                      case 3: ?>  
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                      <?php break;
                            case 4:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <?php break;
                            case 5:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                           <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                        <?php 
                        break;
                        default: ?>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <?php }?>
                      </ul>
                    </small>
                    <small class="col-sm-2">
                        Вежливость: 
                        <ul class="swatches Color">
                        <?php switch ($feedback['politeness']){
                            case 1:?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <?php break;
                            case 2:
                    ?>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                      <?php
                      break;
                      case 3: ?>  
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                          <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                      <?php break;
                            case 4:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <?php break;
                            case 5:
                  ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                          <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                           <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="15"> </li>
                        <?php 
                        break;
                        default: ?>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="15"> </li>
                        <?php }?>
                      </ul>
                    </small>
                    
                </div> 
                
            </div>    
            <?php } ?>
            <?=  $this->paginationControl($this->feedbacks, 'Sliding', 'pagination.phtml') ?>
        </div>
    <?php } ?>
  </div>

  <!--/.row-->

  <!--/.recommended-->
  
  <div style="clear:both"></div></br>
