<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h3><?= $this->user['username'].' '.$this->user['surname'] ?></h3>
        </div>
        <div class="col-lg-3">
            <img src="<?= $this->baseUrl() ?>/images/users_images/<?= $this->user['image'] ?>" width="150px" >
        </div>
        <div class="col-lg-9">
            <div class="col-lg-12">
                <?php if($this->user['banned'] == 0){?>
                    <button onclick="bann()" id="bannButton">Забанить</button>
                    <button onclick="unBann()" id="unbannButton" style="display: none">Разбанить</button>
                <?php }?>
                <?php if($this->user['banned'] == 1){?>
                    <button onclick="bann()" id="bannButton" style="display: none">Забанить</button>
                    <button onclick="unBann()" id="unbannButton" >Разбанить</button>
                <?php }?>
                
                <button id="halfbunnBut">Полубан</button>
                <button id="halfbunnBut" style="display: none">Снять полубан</button> 
            </div>
            <div class="col-lg-12">
                               
                <strong>Возраст :</strong><?= $this->age ?>
            </div>
            <div class="col-lg-12">
                Создал задач: <?= count($this->tasks); ?>
            </div>
            <?php if($this->customersRating){?>
            <div class="col-lg-12">
                Рейтинг: <?= $this->customersRating; ?>
            </div>
            <?php } ?>
        </div>
        <div class="col-lg-12"></div>
        <div class="col-lg-12">
            <div role="tabpanel">

              <!-- Nav tabs -->
              <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#orders" aria-controls="orders" role="tab" data-toggle="tab">Заказы</a></li>
                
                <li role="presentation"><a href="#private" aria-controls="private" role="tab" data-toggle="tab">Личные данные</a></li>

              </ul>

              <!-- Tab panes -->
              <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="orders">
    <?php if(!$this->tasks){?>
    <h2>Задач нет</h2>
    <?php }else {?>
<table id="perTable" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
               <th>Название</th>
                <th>Создан</th>
                <th>Статус</th>
                <th>Исполнитель</th>
            </tr>
        </thead>    
 
        <tfoot>
            <tr>
                <th>Название</th>
                <th>Создан</th>
                <th>Статус</th>
                <th>Исполнитель</th>
            </tr>
        </tfoot>
        <tbody>
    <?php foreach($this->tasks as $task){?>
            <tr>
                <td><a href="<?= $this->baseUrl().'/admin/tasks/view/id/'.$task['id'] ?>"><?=  $task['title']?></a></td>
                <td><?=  date("i:h d.m.y",$task['created_at']) ?></td>
                <td><?=  $task['status'] ?></td>
                <td>
                    <?php if($task['performer_id']){?>
                    <a href="<?= $this->baseUrl().'/admin/performers/view/id/'.$task['performer_id'] ?>"><?= $task['u_username'].' '.$task['u_surname'] ?>
                    </a>
                    <?php }else{?>
                    Пока не назначен
                    <?php } ?>
                </td>
                
            </tr>

    <?php } ?>
 </tbody>
</table>
<?php } ?>
<script>
    $(document).ready(function(){
        $('#perTable').DataTable();
    });

</script>    
                </div>

                <div role="tabpanel" class="tab-pane" id="private">
                    <div class="col-lg-12">
                        <strong>Номер телефона:</strong> <?= $this->user['phonenumber'] ?>
                    </div>
                    <div class="col-lg-12">
                        <strong>Email:</strong> <?= $this->user['email'] ?>
                    </div>
                    <div class="col-lg-12">
                        <strong>Город:</strong> <?= $this->user['city'] ?>
                    </div>
                    <div class="col-lg-12">
                        <strong>Дата рождения:</strong> <?= $this->birthDate ?>
                    </div>
                </div>

              </div>

            </div>
        </div>    
    </div>
</div>

<script>
    function bann(){
        var id = '<?= $this->user['id'] ?>';
$.ajax({
  type: 'POST',
  url: '<?= $this->baseUrl.'/admin/performers/bann/'; ?>',
  data: {id: id},
  success: function(){
      $('#bannButton').hide();
      $('#unbannButton').show();
  }
});       
    }
    function unBann(){
    var id = '<?= $this->user['id'] ?>';
$.ajax({
  type: 'POST',
  url: '<?= $this->baseUrl.'/admin/performers/unbann/'; ?>',
  data: {id: id},
  success: function(){
      $('#bannButton').show();
      $('#unbannButton').hide();
  }
});       
    }    
</script> 