<div class="row">
<form enctype="multipart/form-data"  method="post" action="<?= $this->baseUrl().'/admin/main-banner/add' ?>">
  <div class="col-sm-12" style="padding-bottom: 10px">
  <div class="col-sm-4">
    <input type="file" name="image" class="form-control">
   </div><div class="col-sm-8"></div> </div> 
   <div class="col-sm-12" style="padding-bottom: 10px">
<!--   <div class="col-sm-4">
    <input type="text" name="text" class="form-control">
   </div> <div class="col-sm-8"></div></div> -->
   <div class="col-sm-12" style="padding-bottom: 10px">
    <div class="col-sm-4">
    <input type="submit" class="btn btn-primary" name="submit" value="создать">
    </div><div class="col-sm-8"></div></div> 
</form>
</div>