<a href="<?= $this->baseUrl().'/admin/main-banner/add/' ?>" class="btn btn-primary"> + добавить</a>
<?php if(!$this->slides){?>
<h2>Не найдено ниодного слайда</h2>
<?php }else {?>

<table id="customersTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>#</th>
                <th>Изображение</th>
                
                <th>Удаление</th>
            </tr>
        </thead>    
 
        <tfoot>
            
        </tfoot>
        <tbody>
    <?php foreach($this->slides as $slide){?>
            <tr id="tr<?= $slide['id'] ?>">
                <td><?= $slide['id'] ?></td>
                <td><img src="<?= $this->baseUrl().'/images/main-banner/'.$slide['image'] ?>" height="100"></td>
               
                <td>
                    <button id="removeBut<?= $slide['id'] ?>" onclick="removeSlide(<?= $slide['id'] ?>)" class="btn btn-primary" >Удалить</button>
                    <img id="prel<?= $slide['id'] ?>" src="<?= $this->baseUrl().'/images/blue_preloader.gif' ?>" width="50" style="display: none">
                </td>
                
            </tr>

    <?php } ?>
 </tbody>
</table>
<?php } ?>
<script>
    $(document).ready(function(){
        $('#customersTable').DataTable();
        
        
    });
 function removeSlide(slideId){
     $('#removeBut'+slideId).hide();
     $('#prel'+slideId).show();
     $.ajax({
      type: 'POST',
      url: '<?= $this->baseUrl.'/admin/main-banner/remove-slide/'; ?>',
      data: {
          slideId: slideId
      },
      success: function(data){
         $('#tr'+slideId).remove();
      }
    }); 
    }
</script>