                    
    <div class="row">
        <div class="breadcrumbDiv col-lg-12">
              <ul class="breadcrumb">
                  <li> <a href="<?= $this->baseUrl() ?>">Главная</a> </li>
                 <li class="active" ><?= $this->user['username']." ".mb_substr($this->user['surname'], 0, 1, 'utf-8').'.'?></li>
              </ul>
        </div>
    </div>
    <div class="row transitionfx">
  
   <!-- left column -->
    <div class="col-lg-6 col-md-6 col-sm-6">
    	<!-- product Image and Zoom -->

    <div class="main-image sp-wrap col-lg-12 no-padding style2 style2look2" style="display: inline-block;"> 
         
        
         
    <div class="sp-large" style="left: 0px; top: 0px;">
            <img width="100%" src="<?= $this->baseUrl() ?>/images/users_images/<?= $this->user['image'] ?>" class="img-responsive" alt="img" />

    </div>
    </div>
    </div><!--/ left column end -->
    
    
    <!-- right column -->
    <div class="col-lg-6 col-md-6 col-sm-5">
    
      <h1 class="product-title"><?= $this->user['username']." ".mb_substr($this->user['surname'], 0, 1, 'utf-8').'.'?></h1>
      <h3 class="product-code">Возраст : <?php $unixAge = time() - $this->user['birth_date'];
                $unixYears = $unixAge/31536000;
                $age = floor($unixYears);
                ?>
                <?= $age;  ?> лет
      </h3>
      <h3 class="product-code">Пол :
            <?php if($this->user["sex"] == 'male'){?>
                   М
            <?php }else if($this->user['sex'] == 'female'){ ?>
                   Ж
            <?php } ?>
      </h3>
      <h3 class="product-code">Город :
            <?= $this->user['city'] ?>
      </h3>
      <div class="product-price"> 
          <span class="price-sales">
              Создано задач:  <?php $customersTasksAmount = count($this->tasks); ?>
              <?= $customersTasksAmount; ?>
          </span>  
      </div>
      <?php if($this->user['fb'] || $this->user['ok'] || $this->user['vk']){?>
      <div class="product-share clearfix">
        <p> Привязка к соцсетям </p>
        <div class=""> 
            <?php if($this->user['fb']){?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан" width="40px" src="<?= $this->baseUrl().'/ico/fb.png' ?>" >
            <?php } ?>
            <?php if($this->user['ok']){?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан" width="40px" src="<?= $this->baseUrl().'/ico/ok.png' ?>" >
            <?php } ?>
            <?php if($this->user['vk']){?>
                <img data-toggle="tooltip" data-placement="left" title="Аккаунт привязан"  width="40px" src="<?= $this->baseUrl().'/ico/vk.png' ?>" >
            <?php } ?>
        </div>
      </div>
      <?php } ?>

  
      
      <div class="clear"></div>

      
      <div style="clear:both"></div>

      
      <div class="clear"></div>

      
    
    <?php if($this->customersRating){ ?>
      <div class="color-details"> <span class="selected-color"><strong>Рейтинг</strong></span>
        <ul class="swatches Color">
            <?php switch ($this->customersRating){
                case 1:?>
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
              <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
              <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
              <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <?php break;
                case 2:
        ?>
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
              <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
              <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <?php
          break;
          case 3: ?>  
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
              <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
          <?php break;
                case 4:
      ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <?php break;
                case 5:
      ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
              <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
               <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
            <?php 
            break;
            default: ?>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
            <?php }?>
          </ul>
      </div>
      <?php } ?>
    </div><!--/ right column end -->

  </div>
    <div class="row">
        <div calss="col-lg-12" style="padding-bottom: 5px; padding-top:5px">
             <div class="product-share clearfix"></div>
      <?php if($this->feedbacks){?>
        <div class="row">
        <div class="col-lg-12" style="padding-bottom: 10px">
            <h3 class="block-title-3">
                Отзывы  
            </h3>
            <?php foreach($this->feedbacks as $feedback){?>
            <div class="col-sm-12">
            <div class="col-lg-3"> 
                <?php if($feedback['kind'] == 'negative'){ ?>
                        <p class="text-danger">Отрицательный</p>
                <?php }else{?>
                        <p class="text-success">Положительный</p>
                        <span class="selected-color"><strong>Оценка</strong></span>
                        <ul class="swatches Color">
                                    <?php switch ($feedback['rating']){
                                        case 1:?>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <?php break;
                                        case 2:
                                ?>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                  <?php
                                  break;
                                  case 3: ?>  
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                  <?php break;
                                        case 4:
                              ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <?php break;
                                        case 5:
                              ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                       <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="37"> </li>
                                    <?php 
                                    break;
                                    default: ?>
                                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="37"> </li>
                                    <?php }?>
                                  </ul>
                                  <?php } ?>

            </div>
            <div class="col-lg-2">
                <img class="img-thumbnail" width="100%" src="<?= $this->baseUrl().'/images/users_images/'.$feedback['u_image'] ?>">
            </div>
            <div class="col-lg-7"> 
                <h2><?=  $feedback['u_username'].' '.mb_substr($feedback['u_username'], 0, 1, 'utf-8').'.'?></h2>
                    <p><?= $feedback['text'] ?></p>
                    <h3 class="product-code"><?= date("d.m.Y",$feedback['created']); ?></h3>
            </div>
            </div>
            <?php } ?>
            <?=  $this->paginationControl($this->feedbacks, 'Sliding', 'pagination.phtml') ?>
        </div>
      <!--/row end--> 
      
    </div>
    <div class="col-lg-3 col-md-3 col-sm-5"> </div>
  </div>
      <?php }else{?>
        Отзывов пока нет
      <?php } ?> 
        <div class="color-details"></div>
        </div>
    </div>



<script>
$(document).ready(function(){

    $('#table').DataTable();

    $( "#bi" ).datepicker();
 

}); 

$(function () {
  $('[data-toggle="tooltip"]').tooltip();
}) 

function changeCategory(catId){ 
    if($('#check'+catId).is(':checked')){
        $('#prel'+catId).show();
        $.ajax({
          type: 'POST',
          url: '<?= $this->baseUrl.'/performer/settings/add-user-category'; ?>',
          data: {catId: catId},
          success: function(){
              $('#prel'+catId).hide();
          }
        });  
    }else{
    $('#prel'+catId).show();
        $.ajax({
          type: 'POST',
          url: '<?= $this->baseUrl.'/performer/settings/remove-users-category'; ?>',
          data: {catId: catId},
          success: function(data){
              $('#prel'+catId).hide();
          }
        });
    }

}

function removeTask(id){
$('#remPrel'+id).show();
$.ajax({
  type: 'POST',
  url: '<?= $this->baseUrl.'/performer/task/remove-task/'; ?>',
  data: {id: id},
  success: function(response){
      $('#remPrel'+id).hide();
      $('#tr'+id).remove();
  }
});   
}
</script>    
