<div class="col-lg-12">
    <h3><?= $this->user['username'].' '.$this->user['surname'] ?></h3>
</div>
<div class="col-lg-12">
    <div class="col-lg-6">
       <img src="<?= $this->baseUrl().'/images/task_images/'.$this->user['image'] ?>" class="img-thumbnail" width="200px">
    </div>
    <div class="col-lg-6">
        <div class="col-lg-12">
            <label>Пол: </label>
            <?php if($this->user["sex"] == 'male'){?>
                   Ж
            <?php }else if($this->user['sex'] == 'female'){ ?>
                   М
            <?php } ?>
        </div>
        <div class="col-lg-12">
            <label>Город : </label>
            <?= $this->user['city'] ?>
        </div>
        <div class="col-lg-12">
            <label>Дата рождения : </label>
            <?= date("d.m.Y",$this->user['birth_date']) ?>
        </div>
        <div class="col-lg-12">
            rejting
        </div>
        <div class="col-lg-12">
            Количество задач
        </div>
    </div>
</div>
<div class="col-lg-12">
<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#tasks" aria-controls="tasks" role="tab" data-toggle="tab">Задачи</a></li>
    <li role="presentation"><a href="#feedback" aria-controls="feedback" role="tab" data-toggle="tab">Отзывы</a></li>
    
   
  </ul>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="tasks">
        <?php if($this->tasks){?>
        <!-- Tab panes -->
        <div class="tab-content">
              <table id="tasksTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                      <thead>
                          <tr>
                              <th>Название</th>
                              <th>Статус</th>
                              <th>Категория</th>
                              <th>Дата создания</th>
                              <th>Дата выполнения</th>
                              <th>Цена заказчика</th>
                          </tr>
                      </thead>    

                      <tbody>
                  <?php foreach($this->tasks as $task){?>
                          <tr>
                              <td><?= $task['title'] ?></td>
                              <td><?= $task['status']?></td>
                              <td><?= $task['cat_title'] ?></td>
                              <td><?= date("d.m.Y", $task['created_at']) ?></td>
                              <td><?= date("d.m.Y", $task['final_date']) ?></td>
                              <td><?= $task['customers_price'] ?></td>
                          </tr>

                  <?php } ?>
               </tbody>
              </table>
          </div>
        <?php }else{?>
            Задач не найдено
        <?php }?>
    </div>
    <div role="tabpanel" class="tab-pane" id="feedback">
      Список отзывы
    </div>

  </div>

</div>    
</div>
<script>
    $(document).ready(function(){
        $('#tasksTable').DataTable();
    });
</script>