<div class="col-lg-12">
    <h3><?= $this->user['username'].' '.$this->user['surname'] ?></h3>
</div>
<div class="col-lg-12">
    <div class="col-lg-6">
       <img src="<?= $this->baseUrl().'/images/task_images/'.$this->user['image'] ?>" class="img-thumbnail" width="200px">
    </div>
    <div class="col-lg-6">
        <div class="col-lg-12">
            <label>Пол: </label>
            <?php if($this->user["sex"] == 'male'){?>
                   Ж
            <?php }else if($this->user['sex'] == 'female'){ ?>
                   М
            <?php } ?>
        </div>
        <div class="col-lg-12">
            <label>Город : </label>
            <?= $this->user['city'] ?>
        </div>
        <div class="col-lg-12">
            <label>Дата рождения : </label>
            <?= date("d.m.Y",$this->user['birth_date']) ?>
        </div>
        <div class="col-lg-12">
            rejting
        </div>
        <div class="col-lg-12">
            Количество задач
        </div>
    </div>
</div>
<div class="col-lg-12">
<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#tasks" aria-controls="tasks" role="tab" data-toggle="tab">Задачи</a></li>
    <li role="presentation"><a href="#feedback" aria-controls="feedback" role="tab" data-toggle="tab">Отзывы</a></li>
    
   
  </ul>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="tasks">
        <?php if($this->tasks){?>
        <!-- Tab panes -->
        <div class="tab-content">
              <table id="tasksTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                      <thead>
                          <tr>
                              <th>Название</th>
                              <th>Статус</th>
                              <th>Категория</th>
                              <th>Дата создания</th>
                              <th>Дата выполнения</th>
                              <th>Цена заказчика</th>
                          </tr>
                      </thead>    

                      <tbody>
                  <?php foreach($this->tasks as $task){?>
                          <tr>
                              <td><?= $task['title'] ?></td>
                              <td><?= $task['status']?></td>
                              <td><?= $task['cat_title'] ?></td>
                              <td><?= date("d.m.Y", $task['created_at']) ?></td>
                              <td><?= date("d.m.Y", $task['final_date']) ?></td>
                              <td><?= $task['customers_price'] ?></td>
                          </tr>

                  <?php } ?>
               </tbody>
              </table>
          </div>
        <?php }else{?>
            Задач не найдено
        <?php }?>
    </div>
    <div role="tabpanel" class="tab-pane" id="feedback">
      <?php if($this->feedbacks){?>
        <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
      
      <div class="row userInfo">
        <div class="col-lg-12">
          <h2 class="block-title-2"> Отзывы о заказчике </h2>
        </div>
        <div class="col-xs-12 col-sm-12">
          <table>
            <tbody>
             <?php foreach($this->feedbacks as $feedback){?>
              <tr class="CartProduct">
                <td style="width:10%" class="CartProductThumb">
                    <div>
                        <a href="product-details.html">
                <img src="<?= $this->baseUrl().'/images/users_images/'.$feedback['u_image'] ?>" alt="img">
                        </a>
                    </div>
                </td>
                <td style="width:20%"><div class="CartDescription">
                    <h4> <a href="#"><?= $feedback['t_title'] ?></a> </h4>
                    <span class="size">
                        <?php if($feedback['kind'] == 'positive'){?>
                        Положительный
                        <?php }else{ ?>
                        Отрицательный
                        <?php }?>
                    </span>
                    <div class="price"> <span><?= $feedback['rating'] ?> баллов</span> </div>
                  </div>
                </td>
                <td style="width:75%"><p><?= $feedback['text'] ?></p></td>

                
              </tr>
             <?php } ?>
            </tbody>
          </table>
        </div>
        
<!--        <div class="col-lg-12 clearfix">
          <ul class="pager">
            <li class="previous pull-right"><a href="index.html"> <i class="fa fa-home"></i> Go to Shop </a></li>
            <li class="next pull-left"><a href="account.html"> ← Back to My Account</a></li>
          </ul>
        </div>-->
        
      </div>
      <!--/row end--> 
      
    </div>
    <div class="col-lg-3 col-md-3 col-sm-5"> </div>
  </div>
      <?php }else{?>
        Отзывов пока нет
      <?php } ?>  
    </div>

  </div>

</div>    
</div>
<script>
    $(document).ready(function(){
        $('#tasksTable').DataTable();
    });
</script>