<div class="col-lg-12 col-md-12 col-sm-12">
      <div class="w100 clearfix category-top">
        <h2> Исполнители </h2>
        
      </div>

      <!--/.subCategoryList-->
 <?php if($this->performers){?>
      <div class="w100 productFilter clearfix">
        <div class="pull-right ">
            <div class="change-order pull-left">
              <select class="form-control selectpicker" onchange="changeSortOption()"  name="category" id="categorySelect">
                <option value="0" selected="selected">Все категории</option>
                  <?php foreach($this->categories as $category){?>
                          <option value="<?= $category['id'] ?>" <?php if($this->ctegoryId == $category['id']){?> selected <?php } ?>><?= $category['title'] ?></option>
                
                <?php } ?> 
              </select>
            </div>
<!--          <div class="change-view pull-right">
              <a href="#" title="List" id="listView" class="list-view">
                  <i class="fa fa-th-list"></i>
              </a> 
              <a href="#" title="Grid" class="grid-view">
                  <i class="fa fa-th-large"></i>
              </a>
              
          </div>-->
        </div>
      </div>
      <!--/.productFilter-->
      <div class="row  categoryProduct xsResponse clearfix">
          <?php if(!empty($this->performers)){?>
        <?php foreach($this->performers as $performer){?>  
                 <div class="item col-lg-3 col-md-3 col-sm-4 col-xs-6 productBlock list-view">

            <div class="col-sm-2">
              
               <a href="<?= $this->baseUrl().'/default/performers/view/id/'.$performer['u_id']  ?>">
                   <div style="background: center no-repeat url('<?= $this->baseUrl().'/images/users_images/'.$performer['u_image'] ?>'); height:122px; width: 160px; background-size: contain; margin-top: 10px" src="" alt="img" class="img-thumbnail img-responsive"></div>     
                    </a>  
              
            </div>
            <div class="col-sm-10">
                <div class="col-sm-9">                
                    <h4 style="margin-top: 15px !important">
                        <a href="<?= $this->baseUrl().'/default/performers/view/id/'.$performer['u_id']  ?>">
                            <?= $performer['u_username'].' '.mb_substr($performer['u_surname'], 0, 1, 'utf-8').'.' ?>
                        </a>
                    </h4>
                </div>
                <div class="col-sm-3">                
                                        <?php  
                        $tasksObj = new Performer_Model_DbTable_TasksModel();
                        $performersTasks = $tasksObj->getPerformersTasks($performer['u_id']);
                        $tasksAmount = count($performersTasks);
                        if($tasksAmount > 0){
                            $feedbackObj = new Performer_Model_DbTable_FeedbackModel();
                            $rating = $feedbackObj->countPerformersRating($performer['u_id']);       
                    ?>
                    <ul class="swatches Color">
                    <?php switch ($rating){
                        case 1:?>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <?php break;
                        case 2:
                ?>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                  <?php
                  break;
                  case 3: ?>  
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                      <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                  <?php break;
                        case 4:
              ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <?php break;
                        case 5:
              ?>      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                      <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                       <li> <img src="<?= $this->baseUrl().'/images/pos_star.png' ?>" height="27"> </li>
                    <?php 
                    break;
                    default: ?>
                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                    <li > <img src="<?= $this->baseUrl().'/images/neg_star.png' ?>" height="27"> </li>
                        <?php } }?>
                  </ul>
                </div>
                <div class="col-sm-12"> 
                    <small>Выполненых задач: <?= $tasksAmount ?> </small>
                </div>
                <div class="col-sm-12"> 
                    <p><?= $performer['u_about']?> </p>
                </div>
            
              </div>

        </div>
 
        <?php } ?>
        <?php }else{ ?>
          <h4>Исполнителей по данной категории пока нет</h4>
        <?php } ?>
        <!--/.item-->
      </div>
      <!--/.categoryProduct || product content end-->
      
      <div class="w100 categoryFooter">
        <div class="pagination pull-left no-margin-top">
          <?=  $this->paginationControl($this->performers, 'Sliding', 'pagination.phtml') ?>
        </div>
        <div class="pull-right pull-right col-sm-4 col-xs-12 no-padding text-right text-left-xs">
          
        </div>
      </div>
      <!--/.categoryFooter--> 
 <?php }else{?>
      <div class="col-sm-12">
          <h3>Открытых задач пока нет</h3>
      </div>    
 <?php } ?>     
    </div>
<script>
function changeSortOption(){
    var category = $('#categorySelect :selected').val();
    window.location.href = '<?= $this->baseUrl() ?>/default/performers/index/categoryId/'+category+'/';
    
}
</script>