<?php $message = new Zend_Session_Namespace('result'); ?>
<?php if($message->fail){?>
  <p class="text-danger"><?= $message->fail ?></p>
<?php } ?>
<?php if($message->success){?>
  
  <p class="text-success"><?= $message->success ?></p>
  
<?php } ?>
  <a href="<?= $this->baseUrl().'/admin/category' ?>">Список категорий</a></br>
  <img src="<?= $this->baseUrl().'/images/category_images/'.$this->category['image'] ?>" class="img-thumbnail">
<?= $this->form; ?>