<table id="categoryTable" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Название</th>
                <th>Удаление</th>
                <th>Правка</th>
                
            </tr>
        </thead>    
 
        <tfoot>
            <tr>
                <th>Название</th>
                <th>Удаление</th>
                <th>Правка</th>
            </tr>
        </tfoot>
        <tbody>
<?php foreach($this->categoryList as $category){?>
     <tr id="div<?= $category['id'] ?>">
       <td>
        <?= $category['title']?>
       </td>
       <td>
           <a id="removeBut<?= $category['id'] ?>" onclick="removeCategory(<?= $category['id'] ?>)">Удалить</a>
           <img style="display: none" id="preloader<?= $category['id'] ?>" src="<?= $this->baseUrl()?>/images/blue_preloader.gif" width="40">
       </td>
       <td>
           <a href="<?= $this->baseUrl().'/admin/category/edit-category/id/'.$category['id']?>">Редактировать</a>
       </td>
     </tr>   
<?php } ?>
 </tbody>
</table>
<script>
        $(document).ready(function(){
        $('#categoryTable').DataTable();
    });
function removeCategory(id){
    $('#removeBut'+id).remove();
    $('#preloader'+id).show();
$.ajax({
  type: 'POST',
  url: '<?= $this->baseUrl.'/admin/category/remove-category/'; ?>',
  data: {id: id},
  success: function(data){
    $('#preloader'+id).remove();
    $('#div'+id).remove();
  }
});
}
</script>
