<div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
          <li> <a href="<?= $this->baseUrl() ?>">Главная</a> </li>
        <li class="active">Задачи </li>
      </ul>
    </div>
<div class="col-lg-12 col-md-12 col-sm-12">
    <div class="w100 clearfix category-top">
        <h2> Задачи </h2>
        
      </div>
      <!--/.subCategoryList-->
      
      <div class="w100 productFilter clearfix">
<!--        <p class="pull-left"> Showing <strong>12</strong> products </p>-->
        <div class="pull-right ">

          <div class="change-view pull-right"> 
              <a href="#" title="Grid" class="grid-view">
                  <i class="fa fa-th-large"></i
              </a>
              <a href="#" title="List" id="listView" class="list-view ">
                  <i class="fa fa-th-list"></i>
              </a> 
          </div>
        </div>
      </div>
      <!--/.productFilter-->
      <div class="row  categoryProduct xsResponse clearfix">

        <!--/.item-->
       <?php foreach($this->paginator as $task){?>
        <!--/.item-->
        <div class="item col-lg-3 col-md-3 col-sm-4 col-xs-6 productBlock list-view">

            <div class="col-sm-2">
               <a href="#" data-toggle="modal" data-target="#ModalSignup" >
               <?php if($task['par_cat_image']){?>   
                  <div style="background: center no-repeat url('<?= $this->baseUrl().'/images/category_images/'.$task['par_cat_image'] ?>'); height:122px; width: 160px; background-size: contain; margin-top: 15px" src="" alt="img" class="img-thumbnail img-responsive"></div>
                <?php } ?>   
              </a>
            </div>
            <div class="col-sm-10">
                <div class="col-sm-8">                
                    <h4 style="margin-top: 15px !important">
                        <a href="#" data-toggle="modal" data-target="#ModalSignup" >
                         <?= $task['title'] ?>
                        </a>
                    </h4>
                </div>
                <div class="col-sm-4">                
                    <h4 style="margin-top: 15px !important"> <span><?= $task['price'] ?> <?= POINT_LABEL ?></h4>
                </div>
                <div class="col-sm-12"> 
                    <small>Дата исполнения: <?= date( "d.m.Y" ,$task['final_date']) ?> </small>
                </div>
                <div class="col-sm-12"> 
                    <p><?= $task['description']?> </p>
                </div>
            
                <div class="col-sm-9"> 
                    </div>
                <div class="col-sm-3"> 
                    <div class="action-control">
                        <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#ModalSignup">
                            <span class="add2cart"> Подробнее </span>
                        </a>
                    </div>
                </div>
              </div>

        </div>

       <?php }?>
        <!--/.item--> 
      </div>
      <!--/.categoryProduct || product content end-->
      
      <div class="w100 categoryFooter">
        <div class="pagination pull-left no-margin-top">
          <?= $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml') ?>
        </div>
<!--        <div class="pull-right pull-right col-sm-4 col-xs-12 no-padding text-right text-left-xs">
          <p>Showing 1–450 of 12 results</p>
        </div>-->
      </div>
      <!--/.categoryFooter--> 
    </div>