<div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
          <li> <a href="<?= $this->baseUrl() ?>">Главная</a> </li>
        <li class="active">Задачи </li>
      </ul>
    </div>
<div class="col-lg-12 col-md-12 col-sm-12">
    <div class="w100 clearfix category-top">
        <h2> Задачи </h2>
        
      </div>
      <!--/.subCategoryList-->
      
      <div class="w100 productFilter clearfix">
<!--        <p class="pull-left"> Showing <strong>12</strong> products </p>-->
        <div class="pull-right ">

          <div class="change-view pull-right"> 
              <a href="#" title="Grid" class="grid-view">
                  <i class="fa fa-th-large"></i
              </a>
              <a href="#" title="List" id="listView" class="list-view ">
                  <i class="fa fa-th-list"></i>
              </a> 
          </div>
        </div>
      </div>
      <!--/.productFilter-->
      <div class="row  categoryProduct xsResponse clearfix">

        <!--/.item-->
        <?php foreach($this->paginator as $task){?>
        <div class="item col-sm-4 col-lg-4 col-md-4 col-xs-6 list-view">
          <div class="product">
            <div class="image">  
                <a href="#" data-toggle="modal" data-target="#ModalLogin" style="max-height: 170px !important;" >
                    <img src="<?= $this->baseUrl() ?>/images/task_images/<?= $task['task_image'] ?>" alt="img" class="img-responsive"></a>
<!--                <div class="promotion"> <span class="new-product"> NEW</span> </div>-->
            </div>
            <div class="description">
              <h4><a href="#" data-toggle="modal" data-target="#ModalLogin"><?= $task['title'] ?></a></h4>
              <small>Дата исполнения: <?= date("h:00 d.m.y",$task['final_date']) ?></small></br>
                  
              <div class="grid-description">
                <p><?= $task['description'] ?></p>
              </div>
              
              
            </div>
            <div class="price"> <span><?= $task['customers_price'] ?> .руб</span> </div>
            <div class="action-control"> <a class="btn btn-primary" data-toggle="modal" data-target="#ModalLogin"> <span class="add2cart"> Посмотреть </span> </a> </div>
          </div>
        </div>
        <?php } ?>
        <!--/.item--> 
      </div>
      <!--/.categoryProduct || product content end-->
      
      <div class="w100 categoryFooter">
        <div class="pagination pull-left no-margin-top">
          <?= $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml') ?>
        </div>
<!--        <div class="pull-right pull-right col-sm-4 col-xs-12 no-padding text-right text-left-xs">
          <p>Showing 1–450 of 12 results</p>
        </div>-->
      </div>
      <!--/.categoryFooter--> 
    </div>