<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<div class="container">
    <div class="row">
      <div class="col-sm-12">
        <form class="form-inline">
           
          <div class="form-group" style="padding-bottom: 15px">
            <p id="codeError" style="display: none" class="text-danger">Неверный код</p>
            <div class="input-group">
              <input type="text" class="form-control" id="code" placeholder="код">
              
            </div>
          </div>
</br>
            
          <div class="form-group">
            <p id="phoneVerificationError" style="display: none" class="text-danger">Нет такого номера</p>
            <div class="input-group">
              <div class="input-group-addon">+375</div>
              <input  type="text" class="form-control" id="phoneNum" placeholder="телефон">
              
            </div>
          </div>
          </div>
        <div class="col-sm-12" style="padding-top: 10px">
          <button class="btn btn-primary" id="activation">Активация</button>
          <img id="activatePrel" src="<?= $this->baseUrl().'/images/blue_preloader.gif' ?>" width="60" style="display: none">
        <p id="successMesssage" style="display: none" class="text-success">Номер телефона успешно верифицирован.
              <?php if(!Zend_Auth::getInstance()->hasIdentity()){?>
                <a  href="#"  data-toggle="modal" data-target="#ModalLogin" >
                    Пожалуйста авторизуйтесь.
                </a>
              <?php }else{?>
                <a href="<?= $this->baseUrl().'/customer/office/' ?>">Перейдите в личный кабинет</a>
              <?php } ?>
          </p>

          </form>
          
        </div>
    </div>
</div>  
<script>
$(document).ready(function(){
    $('#activation').bind("click", function(e){
        e.preventDefault();
        var phone = $('#phoneNum').val();
        var code = $('#code').val();
        if(phone == ''){
            $('#phoneVerificationError').show();
        }
        if(code == ''){
            $('#codeError').show();
        }
        if(code != '' && phone != ''){
            activatePhone(phone, code);
        }
    });
});

function activatePhone(phone, code){
$('#codeError').hide();
$('#phoneVerificationError').hide();
$('#activation').hide();  
$('#activatePrel').show();
$.ajax({
    type: 'POST',
    url: '<?= $this->baseUrl.'/phone-activation/activate-account'; ?>',
    data: {phone: phone, code: code},
    success: function(data){
        data = JSON.parse(data);
        if(data.code === '0' || data.phone === '0'){
              if(data.code === '0'){
                  $('#codeError').show();
                }    
              if(data.phone === '0'){
                  $('#phoneVerificationError').show();
                }  
                $('#activation').show();  
                $('#activatePrel').hide();
        }else{
        // the ajax activates user account console.log(data);
            $.ajax({
                type: 'POST',
                url: '<?= $this->baseUrl.'/registration/activate-account-by-phone'; ?>',
                data: {userId: data.user_id},
                success: function(data){
//                    $('#activation').show();  
                    $('#activatePrel').hide();
                    $('#successMesssage').show();
              }
            });
        }
  }
});
}
</script>