<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Fav and touch icons -->

<script type="text/javascript" src="<?= $this->baseUrl() ?>/assets/js/jquery/1.8.3/jquery.js"></script>
<script src="<?= $this->baseUrl() ?>/datatable/js/datatable.js"></script>
<script src="<?= $this->baseUrl() ?>/highslide/highslide-full.js"></script>
<link href="<?= $this->baseUrl() ?>/highslide/highslide.css" rel="stylesheet">
<link href="<?= $this->baseUrl() ?>/datatable/css/datatable.css" rel="stylesheet">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?= $this->baseUrl() ?>/assets/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?= $this->baseUrl() ?>/assets/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?= $this->baseUrl() ?>/assets/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="<?= $this->baseUrl() ?>/ico/apple-touch-icon-57-precomposed.html">
<link rel="shortcut icon" href="<?= $this->baseUrl() ?>/assets/ico/favicon.png">
<?php echo $this->headTitle(); ?>
<!-- Bootstrap core CSS -->
<link href="<?= $this->baseUrl() ?>/assets/bootstrap/css/bootstrap.css" rel="stylesheet">

<!-- add theme styles for this template -->
<link id="pagestyle" rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/assets/css/skin-1.css">

<!-- Custom styles for this template -->
<link href="<?= $this->baseUrl() ?>/assets/css/style.css" rel="stylesheet">

<!-- css3 animation effect for this template -->
<link href="<?= $this->baseUrl() ?>/assets/css/animate.min.css" rel="stylesheet">

<!-- styles needed by carousel slider -->
<link href="<?= $this->baseUrl() ?>/assets/css/owl.carousel.css" rel="stylesheet">
<link href="<?= $this->baseUrl() ?>/assets/css/owl.theme.css" rel="stylesheet">

<!-- styles needed by checkRadio -->
<link href="<?= $this->baseUrl() ?>/assets/css/ion.checkRadio.css" rel="stylesheet">
<link href="<?= $this->baseUrl() ?>/assets/css/ion.checkRadio.cloudy.css" rel="stylesheet">

<!-- styles needed by mCustomScrollbar -->
<link href="<?= $this->baseUrl() ?>/assets/css/jquery.mCustomScrollbar.css" rel="stylesheet">

<!-- Just for debugging purposes. -->
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

<!-- include pace script for automatic web page progress bar  -->

<script>
    paceOptions = {
      elements: true
    };
</script>
<script src="<?= $this->baseUrl() ?>/assets/js/pace.min.js"></script>
     <script type="text/javascript">
function swapStyleSheet(sheet){
document.getElementById('pagestyle').setAttribute('href', sheet);
}
</script>    <style>

	.themeControll {
		background:#2d3e50;
		height: auto;
		width:100px;
		position:fixed;
		left:0;
		padding:20px;
		top:20%;
		z-index:999999;
		-webkit-transform: translateX(0);
		-moz-transform: translateX(0);
		-o-transform: translateX(0);
		-ms-transform: translateX(0);
		transform: translateX(0);
		opacity: 1;
		-ms-filter: none;
		filter: none;
		-webkit-transition: opacity .5s linear, -webkit-transform .7s cubic-bezier(.56, .48, 0, .99);
		-moz-transition: opacity .5s linear, -moz-transform .7s cubic-bezier(.56, .48, 0, .99);
		-o-transition: opacity .5s linear, -o-transform .7s cubic-bezier(.56, .48, 0, .99);
		-ms-transition: opacity .5s linear, -ms-transform .7s cubic-bezier(.56, .48, 0, .99);
		transition: opacity .5s linear, transform .7s cubic-bezier(.56, .48, 0, .99);
	}
	
	.themeControll.active {
		display: block;
		-webkit-transform: translateX(-100px);
		-moz-transform: translateX(-100px);
		-o-transform: translateX(-100px);
		-ms-transform: translateX(-1020px);
		transform: translateX(-100px);
		-webkit-transition: opacity .5s linear, -webkit-transform .7s cubic-bezier(.56, .48, 0, .99);
		-moz-transition: opacity .5s linear, -moz-transform .7s cubic-bezier(.56, .48, 0, .99);
		-o-transition: opacity .5s linear, -o-transform .7s cubic-bezier(.56, .48, 0, .99);
		-ms-transition: opacity .5s linear, -ms-transform .7s cubic-bezier(.56, .48, 0, .99);
		transition: opacity .5s linear, transform .7s cubic-bezier(.56, .48, 0, .99);
	
	}
	
	.themeControll a {
    border-radius: 3px;
    clear: both;
    display: block;
    height: 25px;
    margin-bottom: 4px;
    width: 50px;
	}
	
	.tbtn {
    background:#2D3E50;
    color: #FFFFFF !important;
    font-size: 30px;
    height: auto;
    padding: 10px;
    position: absolute;
    right: -40px;
    top: 0;
    width: 40px;
	cursor:pointer;
   }
   
   	@media (max-width: 780px) {
    .themeControll {
        display:none;
    }
}
	
	</style>
    </head>

<body >
<!--    <div class="themeControll">
<h3 style="width: 60px; font-size: 10px; line-height: 12px;" class="uppercase color-white text-center"> Choose your colour </h3>
<a onclick="swapStyleSheet('assets/css/skin-1.css')" style="background:#4ec67f;border-top: 12px solid #27AE60;"> </a>
<a onclick="swapStyleSheet('assets/css/skin-8.css')" style="background:#3BCA95;border-top: 12px solid #34BC8A"> </a>
<a onclick="swapStyleSheet('assets/css/skin-2.css')" style="background:#1ABC9C;border-top: 12px solid #16A085"> </a>
<a onclick="swapStyleSheet('assets/css/skin-3.css')" style="background:#3498DB;border-top: 12px solid #2980B9"> </a>
<a onclick="swapStyleSheet('assets/css/skin-4.css')" style="background:#9B59B6;border-top: 12px solid #9149AF"> </a>
<a onclick="swapStyleSheet('assets/css/skin-5.css')" style="background:#E74C3C;border-top: 12px solid #C0392B"> </a>
<a onclick="swapStyleSheet('assets/css/skin-7.css')" style="background:#95A5A6;border-top: 12px solid #7F8C8D"> </a>
<a onclick="swapStyleSheet('assets/css/skin-9.css')" style="background:#F7B529;border-top: 12px solid #E78E00"> </a>
<a onclick="swapStyleSheet('assets/css/skin-10.css')" style="background:#F17370;border-top: 12px solid #F26663"> </a>
<a onclick="swapStyleSheet('assets/css/skin-11.css')" style="background:#273646;border-top: 12px solid #2ECC71"> </a>
<a onclick="swapStyleSheet('assets/css/skin-6.css')" style="background:#34495E;border-top: 12px solid #283949"> </a>
<h3 style="width: 60px; font-size: 10px; line-height: 12px;" class="uppercase color-white text-center">
<br>
 <a style="color:#fff" href="http://codepeoples.com/tanimdesign.net/thsop-v-1.3/index.html"><i class="fa fa-angle-double-left"></i> Theme Chooser </a> </h3>
<p class="tbtn">  <i class="fa fa-angle-double-left"></i></p>
</div>-->
<?php $user = Zend_Auth::getInstance()->getIdentity();  ?>
<!-- if phone is not verified -->
<div class="modal signUpContent fade" id="ModalPhoneNotVerified" tabindex="-1" role="dialog" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
        <h3 class="modal-title-site text-center" > Не верифицирован </h3>
      </div>
      <div class="modal-body">
          <p>
             Для создания задания подтвердите номер Вашего телефона в личном кабинете
          </p>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Закрыть</button>
      </div>
    </div>
    <!-- /.modal-content --> 
    
  </div>
  <!-- /.modal-dialog --> 
  
</div>

<!-- Modal Forgot start -->
<div class="modal signUpContent fade" id="ModalForgotPass" tabindex="-1" role="dialog" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
        <h3 class="modal-title-site text-center" > Восстановление пароля </h3>
      </div>
      <div class="modal-body">
        <div class="form-group login-username">
            <p id="error" style="display: none" class="text-danger">Пользователь с таким адресом не зарегестрирован</p>
            <p id="success" style="display: none" class="text-success">Проверьте ваш почтовый ящик</p>
          <div >
            <input type="text" class="form-control" id="emailRec" placeholder="Email">
          </div>
        </div>
        <div >
          <div >
            <button id="submit"  onclick="checkEmail()" class="btn  btn-block btn-primary">Восстановить</button>
            <img id="preloader" style="display:none" src="<?= $this->baseUrl() ?>/images/blue_preloader.gif" width="55">
          </div>
        </div>
        <!--userForm--> 
        
      </div>
      <div class="modal-footer">
        <p class="text-center"> Нет аккаунта? <a data-toggle="modal"  data-dismiss="modal" href="#ModalSignup">Зарегистрироваться</a> <br>
        
      </div>
    </div>
    <!-- /.modal-content --> 
    
  </div>
  <!-- /.modal-dialog --> 
  
</div>

<!-- Modal Login start -->
<div class="modal signUpContent fade" id="ModalLogin" tabindex="-1" role="dialog" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
        <h3 class="modal-title-site text-center" > Вход </h3>
      </div>
      <div class="modal-body">
        <div class="form-group login-username">
            <p id="authError" style="display: none" class="required">Неправильный логин и/или пароль</p>
          <div >
            <input name="username" id="login-user" value="" class="form-control input"  size="20" placeholder="Email" type="text">
          </div>
        </div>
        <div class="form-group login-password">
          <div >
            <input name="pass" id="login-password" class="form-control input"  size="20" placeholder="Пароль" type="password">
          </div>
        </div>
        <div >
          <div >
            <button onclick="login()" id="loginButton" class="btn  btn-block btn-lg btn-primary"  >Войти</button>
          </div>
            <script>
            $(document).ready(function(){
                $('#ModalLogin').keyup(function(e){
                    if(e.keyCode == 13)
                    {
                        login();
                    }
    });
            });
            </script>
        </div>
        <div class="form-group">
            <h5 style="padding:10px 0 10px 0;" class="text-center"> ИЛИ </h5>
            <div class="control-group"> <a class="fb_button btn  btn-block btn-lg " href="<?= $this->baseUrl()?>/s-auth/vk-link/">  VK.COM </a> </div></br>
            <div class="control-group"> <a class="fb_button btn  btn-block btn-lg " href="<?= $this->baseUrl()?>/s-auth/fb-link/">  FACEBOOK.COM </a> </div></br>
            <div class="control-group"> <a class="btn  btn-block btn-lg orange" href="<?= $this->baseUrl()?>/s-auth/ok-link/">  OK.RU</a> </div></br>
        </div>
        
        <!--userForm--> 
        
      </div>
      <div class="modal-footer">
        <p class="text-center"> Нет аккаунта? <a data-toggle="modal"  data-dismiss="modal" href="#ModalSignup">Зарегистрироваться</a> <br>
            <a href="#ModalForgotPass" data-toggle="modal"  data-dismiss="modal" > Забыли пароль? </a> </p>
      </div>
    </div>
    <!-- /.modal-content --> 
    
  </div>
  <!-- /.modal-dialog --> 
  
</div>
<!-- /.Modal Login --> 

<!-- Modal Signup start -->
<div class="modal signUpContent fade" id="ModalSignup" tabindex="-1" role="dialog" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
        <h3 class="modal-title-site text-center" > Регистрация </h3>
      </div>
      <div class="modal-footer">
        <p class="text-center"> Уже зарегистрированы? <a data-toggle="modal"  data-dismiss="modal" href="#ModalLogin"> Войти </a> </p>
      </div>
      <div class="modal-body">
        <h5 style="padding:10px 0 10px 0;" class="text-center"> Быстрая регистрация через : </h5>
        <div class="snBlock">
            <div class="control-group"> <a class="fb_button btn  btn-block btn-lg " href="<?= $this->baseUrl()?>/s-auth/vk-link/">  VK.COM </a> </div></br>
            <div class="control-group"> <a class="fb_button btn  btn-block btn-lg " href="<?= $this->baseUrl()?>/s-auth/fb-link/">  FACEBOOK.COM </a> </div></br>
            <div class="control-group"> <a class=" btn  btn-block btn-lg orange" href="<?= $this->baseUrl()?>/s-auth/ok-link/">  OK.RU</a> </div></br>
        </div>
        <h5 style="padding:10px 0 10px 0;" class="text-center"> или через email  </h5>
        <div class="snBlock">
        <div class="form-group reg-username">
          <div >
            <input name="username" id="username"  class="form-control input"  size="20" placeholder="Имя" type="text">
          </div>
            <p class="text-danger" id="usernameError" style="display: none" >* Проверьте вводимые данные</p>
        </div>
        <div class="form-group reg-username">
          <div >
            <input name="surname" id="surname" class="form-control input"  size="20" placeholder="Фамилия" type="text">
          </div>
            <p class="text-danger" id="surnameError" style="display: none" >* Проверьте вводимые данные</p>
        </div>
        <div class="form-group reg-email">
          <div >
            <input name="email" id="email" class="form-control input"  size="20" placeholder="Ваш Email" type="text">
          </div>
            <p class="text-danger" id="mailError" style="display: none">Данный E-mail занят</p>
            <p class="text-danger" id="mailInvalid" style="display: none" >Неправильный email-адрес</p>
        </div>
        <div class="form-group">
          <label class="col-md-4 control-label" for="radios">Пол</label>
          <div class="col-md-4">
              <input name="sex"  value="male"  type="radio" >
              М
          </div>
          <div class="col-md-4">
              <input name="sex" value="female" type="radio" >
              Ж

          </div>
          <p class="text-danger" id="sexError" style="display: none" >* Проверьте вводимые данные</p>
        </div>
        <div>
        <div class="form-group reg-email input-group" style="width: 100%">
          
              <span class="input-group-addon">+375</span>
              <input id="phonenumber" name="phonenumber" class="form-control" placeholder="Номер телефона" type="text">
           <p class="text-danger" id="phoneTaken" style="display: none" >* Данный номер телефона уже занят</p>
            
        </div>
        <p class="text-danger" id="phoneError" style="display: none" >* Проверьте вводимые данные</p>
        </div>
        <div class="form-group reg-email">
          <div >
            <input name="city" id="city" class="form-control input" size="20" placeholder="Город" type="text">
          </div>
            <p class="text-danger" id="cityError" style="display: none" >* Проверьте вводимые данные</p>
        </div>
        <div class="form-group reg-email" >
            <div class="col-sm-12" style="text-align: center">
                <label>Дата рождения</label>
            </div>
            <div class="col-sm-4" style="padding-bottom: 10px">
                <div >
                    <select name="birthYear" id="birth_year"  class="form-control select-list"   placeholder="Дата рождения">
                        <?php for($year = 2010;$year > 1950; $year = $year - 1){?>
                        <option value="<?= $year ?>"><?= $year ?></option>
                        <?php } ?>
                    </select>    
                </div>
            </div>    
            <div class="col-sm-4" style="padding-bottom: 10px">
                <div >
                    <select name="birthMonth" id="birth_мonth"  class="form-control select-list"   placeholder="Дата рождения">
                        <?php for($month = 1; $month < 13; $month++){?>
                        <option value="<?= $month ?>">
                                <?php if($month == 1){?>
                                    январь 
                                <?php }else if($month == 2){?>
                                     февраль
                                <?php }else if($month == 3){?>
                                    март 
                                <?php }else if($month == 4){?>
                                     апрель
                                <?php }else if($month == 5){?>
                                     май 
                                <?php }else if($month == 6){?>
                                     июнь 
                                <?php }else if($month == 7){?>
                                     июль 
                                <?php }else if($month == 8){?>
                                     август 
                                <?php }else if($month == 9){?>
                                     сентябрь
                                <?php }else if($month == 10){?>
                                    октябрь 
                                <?php }else if($month == 11){?>
                                     ноябрь 
                                <?php }else if($month == 12){?>
                                    декабрь
                                <?php } ?>
                        </option>
                        <?php } ?>
                    </select>    
                </div>
            </div>    
            <div class="col-sm-4" style="padding-bottom: 10px">
                <div >
                    <select name="birthDay" id="birth_day"  class="form-control select-list"   placeholder="Дата рождения" >
                        <?php for($day = 1; $day < 32; $day++){?>
                        <option value="<?= $day ?>"><?= $day ?></option>
                        <?php } ?>
                    </select>    
                </div>
            </div>    
          
            <p class="text-danger" id="birthdayError" style="display: none" >* Проверьте вводимые данные</p>
        </div>
        <div class="form-group reg-password">
          <div >
            <input name="pass" id="pass" class="form-control input"  size="20" placeholder="Пароль" type="password">
          </div>
        </div>
        <div class="form-group reg-password">
          <div >
            <input name="passConfirm" id="passConf"  class="form-control input"  size="20" placeholder="Подтвердите пароль" type="password">
          </div>
            <p class="text-danger" id="passError" style="display: none">Пароли не совпадают</p>
        </div>
        </div>
        
<!--        <div class="form-group">
          <div >
            <div class="checkbox login-remember">
              <label>
                <input name="rememberme" id="rememberme" value="forever" checked="checked" type="checkbox">
                Remember Me </label>
            </div>
          </div>
        </div>-->
        <div >
          <div >
            <input name="submit" id="submitReg"  class="btn  btn-block btn-lg btn-primary" value="ЗАРЕГИСТРИРОВАТЬСЯ" type="submit">
            <img id="restrationPreloader" src="<?= $this->baseUrl.'/images/blue_preloader.gif' ?>" width="70" style="display: none" >
          </div>
        </div>
        <!--userForm--> 
        
      </div>

    </div>
    <!-- /.modal-content --> 
    
  </div>
  <!-- /.modal-dialog --> 
  
</div>

<div class="modal signUpContent fade" id="ModalPhoneNotVerifiedBecomeAPer" tabindex="-1" role="dialog" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
        <h3 class="modal-title-site text-center" > Не верифицирован </h3>
      </div>
      <div class="modal-body">
          <p>
             Для подачи заявки на получение статуса исполнителя подтвердите номер Вашего телефона в личном кабинете
          </p>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Закрыть</button>
      </div>
    </div>
    <!-- /.modal-content --> 
    
  </div>
  <!-- /.modal-dialog --> 
  
</div>
<!-- Modal categories settings start -->

        <!--userForm--> 
        
      </div>
      <div class="modal-footer">
        <p class="text-center"> Нет аккаунта? <a data-toggle="modal"  data-dismiss="modal" href="#ModalSignup">Зарегистрироваться</a> <br>
        
      </div>
    </div>
    <!-- /.modal-content --> 
    
  </div>
  <!-- /.modal-dialog --> 
  
</div> 

<!-- Fixed navbar start -->
<div class="navbar navbar-tshop navbar-fixed-top megamenu" role="navigation">
  <div class="navbar-top">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-sm-6 col-xs-6 col-md-6">
          <div class="pull-left ">
            <ul class="userMenu ">
              <li> <a href="#"> <span class="hidden-xs">Телефон поддержки</span><i class="glyphicon glyphicon-info-sign hide visible-xs "></i> </a> </li>
              <li class="phone-number"> <a  href="callto:+8801680531352"> <span> <i class="glyphicon glyphicon-phone-alt "></i></span> <span class="hidden-xs" style="margin-left:5px"> 5552525 </span> </a> </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-6 col-sm-6 col-xs-6 col-md-6 no-margin no-padding">
          <div class="pull-right">
            <ul class="userMenu">
              <?php if(Zend_Auth::getInstance()->hasIdentity()){?>
                <li> <a href="<?= $this->baseUrl().'/customer/office/' ?>"><span class="hidden-xs">Личный кабинет</span> <i class="glyphicon glyphicon-user hide visible-xs "></i></a> </li>
                <li> <a href="<?= $this->baseUrl().'/authentication/log-out/'.$this->userId ?>"  > <span class="hidden-xs">Выйти</span> <i class="glyphicon glyphicon-log-in hide visible-xs "></i> </a> </li>
              <?php }else{ ?>
                <li> <a href="#"  data-toggle="modal" data-target="#ModalLogin"> <span class="hidden-xs">Войти</span> <i class="glyphicon glyphicon-log-in hide visible-xs "></i> </a> </li>
                <li class="hidden-xs"> <a href="#"  data-toggle="modal" data-target="#ModalSignup"> Регистрация </a> </li>
              <?php } ?>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/.navbar-top-->
  
  <div class="container">
    <div class="navbar-header">

        <a class="navbar-brand " href="<?= $this->baseUrl().'/customer/index/' ?>"> <img src="<?= $this->baseUrl() ?>/images/logo.png" alt="TSHOP"> </a> 
      
      <!-- this part for mobile -->
      <div class="search-box pull-right hidden-lg hidden-md hidden-sm">
        <div class="input-group">
          <button class="btn btn-nobg getFullSearch" type="button"> <i class="fa fa-search"> </i> </button>
        </div>
        <!-- /input-group --> 
        
      </div>
    </div>
    

    <!--/.navbar-cart-->
    
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
            <?php if(Zend_Auth::getInstance()->hasIdentity()){?>
                  <li > <a href="<?= $this->baseUrl().'/customer/task/new-task'?>">Заказать услугу</a> </li>
            <?php }else{ ?>
                  <li > <a data-toggle="modal"  data-dismiss="modal" href="#ModalLogin">Заказать услугу</a> </li>
            <?php } ?> 
           <?php if(Zend_Auth::getInstance()->hasIdentity()){?>       
                <li> <a href="<?= $this->baseUrl().'/customer/performers/'?>">Исполнители</a> </li>
                <li> <a href="<?= $this->baseUrl().'/customer/about/'?>">О проекте</a> </li>
                <li> <a href="<?= $this->baseUrl().'/customer/contacts/'?>">Контакты</a> </li>
           <?php }else{?>
                <li> <a href="<?= $this->baseUrl().'/performers/'?>">Исполнители</a> </li>
                <li> <a href="<?= $this->baseUrl().'/about/'?>">О проекте</a> </li>
                <li> <a href="<?= $this->baseUrl().'/contacts/'?>">Контакты</a> </li>
           <?php }?>
          <?php if(Zend_Auth::getInstance()->hasIdentity()){?>
            <?php if( empty($this->application) || $this->application == 0){?>
                  <?php if($user->phone_verified == 1){ ?>
                      <li><a class="blog-nav-item"  href="<?= $this->baseUrl().'/customer/office/application' ?>"  >Стать исполнителем</a></li>
                  <?php }else{?>
                      <li><a data-toggle="modal"  data-dismiss="modal" href="#ModalPhoneNotVerifiedBecomeAPer">Стать исполнителем</a></li>
                  <?php }?>
            <?php }?>
          <?php }?>
        <!-- change width of megamenu = use class > megamenu-fullwidth, megamenu-60width, megamenu-40width -->


      </ul>
      
      <!--- this part will be hidden for mobile version -->

      <!--/.navbar-nav hidden-xs--> 
    </div>
    <!--/.nav-collapse --> 
    
  </div>
  <!--/.container -->
  
<!--  <div class="search-full text-right"> <a class="pull-right search-close"> <i class=" fa fa-times-circle"> </i> </a>
    <div class="searchInputBox pull-right">
      <input type="search"  data-searchurl="search?=" name="q" placeholder="start typing and hit enter to search" class="search-input">
      <button class="btn-nobg search-btn" type="submit"> <i class="fa fa-search"> </i> </button>
    </div>
  </div>-->
  <!--/.search-full--> 
  
</div>
<!-- /.Fixed navbar  -->
<div class="container main-container headerOffset">
     <?php echo $this->layout()->content; ?>
</div>

<footer>
  <div class="footer" id="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-4  col-md-12 col-sm-12 col-xs-12">
          <h3> Поддержка </h3>
          <ul>
            <li class="supportLi">
              <p> При любом вопросе свяжитесь с нами </p>
              <h4> <a class="inline" > <strong> <i class="fa fa-phone"> </i> 88 01680 531352 </strong> </a> </h4>
              <h4> <a class="inline" href="mailto:help@icando.by"> <i class="fa fa-envelope-o"> </i> help@icando.by</a> </h4>
            </li>
          </ul>
        </div>
        
        <div class="col-lg-4  col-md-12 col-sm-12 col-xs-12">
          <h3> Меню </h3>
          <ul>
              <li> <a href="<?= $this->baseUrl().'/customer/office/' ?>"> Кабинет </a> </li>
            <li> <a href="<?= $this->baseUrl().'/customer/performers/' ?>"> Исполнители </a> </li>
            <li> <a href="<?= $this->baseUrl().'/customer/about/' ?>"> О проекте</a> </li>
            <li> <a href="<?= $this->baseUrl().'/customer/contacts/' ?>"> Контакты </a> </li>
          </ul>
        </div>

        <div class="col-lg-4  col-md-12 col-sm-12 col-xs-12">
          <h3> Мы в социальных сетях</h3>
          
          <ul class="social">
            <li> <a href="http://facebook.com/"> <i class=" fa fa-facebook"> &nbsp; </i> </a> </li>
            <li> <a href="http://twitter.com/"> <i class="fa fa-twitter"> &nbsp; </i> </a> </li>
            <li> <a href="https://plus.google.com/"> <i class="fa fa-google-plus"> &nbsp; </i> </a> </li>
            <li> <a href="http://youtube.com/"> <i class="fa fa-pinterest"> &nbsp; </i> </a> </li>
            <li> <a href="http://youtube.com/"> <i class="fa fa-youtube"> &nbsp; </i> </a> </li>
          </ul>
        </div>
          
      </div>
      <!--/.row--> 
    </div>
    <!--/.container--> 
  </div>
  <!--/.footer-->
  
  <div class="footer-bottom">
    <div class="container">
      <p class="pull-left"> &copy; ICANDO.BY 2014. All right reserved. </p>
      <div class="pull-right paymentMethodImg"></div>
    </div>
  </div>
  <!--/.footer-bottom--> 
</footer>


<!--  <div class="modal fade hide" id="modalAds" role="dialog" >
        <div class="modal-dialog  modal-bg-1">
            <div class="modal-body-content">
      		<a class="close" data-dismiss="modal">×</a>
              <div class="modal-body">
              <div class="col-lg-6 col-sm-8 col-xs-8">
               <h3>enter your <br>email to  receive</h3>
               <p class="discountLg">10% OFF </p>
               <p>We invite you to subscribe to our newsletter and receive 10% discount.
               </p>
               
              <div class="clearfx"> <form id="newsletter" class="newsletter">
                           <input type="text" id="subscribe" name="s" placeholder="Enter email">
                                        <button class="subscribe-btn">Subscribe</button>
              </form></div>
              
             <p> <a href="category.html" class="link shoplink"> SHOP NOW <i class="fa fa-caret-right"> </i> </a></p>
              
              
              </div>
              </div>
  
</div>
</div>
</div>-->
<!-- Le javascript
================================================== --> 


<script src="<?= $this->baseUrl() ?>/assets/bootstrap/js/bootstrap.min.js"></script> 

<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
<script>

 // this script required for subscribe modal
$(window).load(function(){
 // full load
 $('#modalAds').modal('show');
 $('#modalAds').removeClass('hide');
});

</script>

<!-- include jqueryCycle plugin --> 
<script src="<?= $this->baseUrl() ?>/assets/js/jquery.cycle2.min.js"></script> 

<!-- include easing plugin --> 
<script src="<?= $this->baseUrl() ?>/assets/js/jquery.easing.1.3.js"></script> 

<!-- include  parallax plugin --> 
<script type="text/javascript"  src="<?= $this->baseUrl() ?>/assets/js/jquery.parallax-1.1.js"></script> 

<!-- optionally include helper plugins --> 
<script type="text/javascript"  src="<?= $this->baseUrl() ?>/assets/js/helper-plugins/jquery.mousewheel.min.js"></script> 

<!-- include mCustomScrollbar plugin //Custom Scrollbar  --> 

<script type="text/javascript" src="<?= $this->baseUrl() ?>/assets/js/jquery.mCustomScrollbar.js"></script> 

<!-- include checkRadio plugin //Custom check & Radio  --> 
<script type="text/javascript" src="<?= $this->baseUrl() ?>/assets/js/ion-checkRadio/ion.checkRadio.min.js"></script> 

<!-- include grid.js // for equal Div height  --> 
<script src="<?= $this->baseUrl() ?>/assets/js/grids.js"></script> 

<!-- include carousel slider plugin  --> 
<script src="<?= $this->baseUrl() ?>/assets/js/owl.carousel.min.js"></script> 

<!-- jQuery minimalect // custom select   --> 
<script src="<?= $this->baseUrl() ?>/assets/js/jquery.minimalect.min.js"></script> 

<!-- include touchspin.js // touch friendly input spinner component   --> 
<script src="<?= $this->baseUrl() ?>/assets/js/bootstrap.touchspin.js"></script> 

<!-- include custom script for only homepage  --> 
<script src="<?= $this->baseUrl() ?>/assets/js/home.js"></script> 
<!-- include custom script for site  --> 
<script src="<?= $this->baseUrl() ?>/assets/js/script.js"></script> 
<script src="<?= $this->baseUrl() ?>/js/scripts.js"></script> 
  <script>

  </script> 
</body>

</html>
