<?php echo $this->doctype(); ?>
<html>
<head>
<?php echo $this->headMeta(); ?>  
    <link rel="icon" href="<?= $this->baseUrl()?>/images/logo.png" type="image/png" />
    <link rel="shortcut icon" href="<?= $this->baseUrl()?>/images/logo.png" type="image/png">
<?php echo $this->headTitle(); ?>    
<!--<?php// echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css');?> -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/desktop/css/reset.css" type="text/css" media="screen">
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/desktop/css/style.css" type="text/css" media="screen">
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/desktop/css/slider.css" type="text/css" media="screen">
        <!-- REVOLUTION BANNER CSS SETTINGS -->
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/desktop/css/responsive.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/desktop/rs-plugin/css/settings.css" media="screen" />
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/desktop/css/carousel.css" type="text/css" media="screen">
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/desktop/css/validationEngine.jquery.css" type="text/css" media="screen">
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/desktop/css/selectik.css" type="text/css" media="screen">
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/desktop/css/touchTouch.css" type="text/css" media="screen">
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/desktop/css/skeleton.css" type="text/css" media="screen">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,600italic,700,700italic,400italic,800,800italic,300italic,300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" title="color shemes" href="<?= $this->baseUrl() ?>/desktop/css/color_themes/f04f00.css" class="theme" id="theme" type="text/css" media="screen">
</head>
<?php $this->headScript()->prependFile($this->baseUrl() . '/js/jq.js')  ?>
<?= $this->headScript() ?>
<body>
    

        <!--======================== Settins Panel ================================-->


        <!-- ======================================================================== -->
        <div class="bg">
            <div class="main">
                <!--==============================header=================================-->
                <header>
                    <div class="container">
                        <div class="three columns">
                            <h1 class="logo">
                                <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index')); ?>">
                                    <img src="<?= $this->baseUrl() ?>/desktop/images/logotype.png" alt="logo-text" />
                                   
                                </a>
                            </h1>
                        </div>
                            <nav class="header_menu">
                                <ul class="sf-menu">
                                    <li>
                                        <a id="index" href="<?= $this->url(array('controller' => 'index', 'action' => 'index')) ?>" >Главная
                                        </a>

                                    </li>
<!--                                    <li><a href="about.html">About Us</a></li>-->
                                    <li >
                                        <a id="services"  href="<?= $this->url(array('controller' => 'service', 'action' => 'category-list'))?>">Услуги
                                        <ul  class="sub-menu">
                                            <li><a id ="sub-menu-link" href="<?= $this->url(array('controller' => 'service', 'action' => 'list-of-services'))?>">Полный список услуг</a></li>
                                            <?php //foreach ($this->categories as $key => $value){
                                            //echo '<li><a id="sub-menu-link" href="'.$this->url(array('controller' => 'service', 'action' => 'service-list-by-category')).'?id='.$value['id'].'">'. $value['title'].'</a></li>'; } ?>
                                            
                                        </ul>
                                    </li>

                                    <li>
                                        <a id="gallery" href="<?= $this->url(array('controller' => 'items', 'action' => 'gallery-items'))?>">Галерея</a></li>
                                    <li>
                                        <a id="feedback" href="<?= $this->url(array('controller' => 'feedback', 'action' => 'feedback-list'))?>">Отзывы</a>
                                        <ul   class="sub-menu">
                                            <li><a id="sub-menu-link" href="<?= $this->url(array('controller' => 'feedback', 'action' => 'feedback-list'))?>">Читать отзывы</a></li>
                                            <?php if(!Zend_Auth::getInstance()->hasIdentity()){?>
                                            <li><a id="sub-menu-link" href="<?= $this->url(array('controller' => 'feedback', 'action' => 'new-feedback'))?>">Оставить отзыв</a></li>
                                            <?php } ?>
                                        </ul>
                                    </li>                                    
                                    <li><a id="contacts" href="<?= $this->url(array('controller' => 'index', 'action' => 'contacts'))?>">Контакты</a></li>
                                </ul>
                                <select id="mobile_menu"></select>
                            </nav>
                           
                        </div>
                        
                           <?php if(Zend_Auth::getInstance()->hasIdentity()){?>
                           <div class="four columns header-buttons-group">
                             <a href="<?php echo $this->url(array('controller'=>'authentication', 'action'=>'log-out'))?>" class="">Выйти</a>
                           </div>
                           <?php }else{ ?>
                           <div class="four columns header-buttons-group">
                                <a href="<?php echo $this->url(array('controller'=>'authentication', 'action'=>'log-in'))?>" class="">Войти</a> 
                           </div></br>
                           <div class="four columns header-buttons-group">     
                                <a href="<?php echo $this->url(array('controller'=>'registration', 'action'=>'index'))?>" class="">Реги</a> 
                           </div></br>
                           <div class="four columns header-buttons-group">     
                                <a href="<?php echo $this->url(array('controller'=>'s-auth', 'action'=>'index'))?>" class="">Соц</a> 
                           </div>
                           <?php }?>
                        
                        <div class="clearfix"></div>
                    </div>
                </header>

                <!--==============================content================================-->
<?php echo $this->layout()->content; ?>
                <!--==============================Aside=================================-->
                <aside>
                    <div class="container">

                        <div class="four columns">
                            <h2 id="bottom_banner">Контакты</h2>
                            <ul class="address">
                                <li class="addr">
                                   <p> ул. Комсомольская 49, 
                                    Щучин
                                    Беларусь</p>
                                </li>
                                <li class="phone">
                                <p >    801514 28013</p>
                                </li>
                                <li class="phone_velc">
                               <p >     +375293143146</p>
                                </li>
                                <li class="phone_mts">
                                <p  >    +375336159609</p>
                                </li>
                                <li class="mail">
                                <p >    kreativ.sch@gmail.com</p>
                                </li>
                                <li class="skype">
                                <p >    Kreativ.sch</p>
                                </li>
                            </ul>
                        </div>

                    </div>
                </aside>
                <!--==============================footer=================================-->
                <footer>
                    <div class="container">
                        <div class="sixteen columns">
                            <div class="fleft">
                                &COPY; Copyright 2013 by creo.of.by . All right reserved
                            </div>

                        </div>
                        <div class="clearfix"></div>
                    </div>
                </footer>

            </div>
        </div>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery-2.0.0.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery-migrate-1.1.1.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/raphael-min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.carouFredSel-6.2.1.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.isotope.min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.validationEngine.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.validationEngine-en.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.form.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.hoverdir.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.selectik.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/touchTouch.jquery.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/settings-panel.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.cookie.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/script.js"></script>
        <script>
            $(document).ready(function(){
                "use strict";
                
                $('.header_menu a').each(function(i){
                    var link = $(this).attr('href');
                    var text;
                    if($(this).parents('ul.sub-menu').length!=0){
                        text = '--'+$(this).text();
                    } else {
                        text = $(this).text();
                    }
                    if(window.location.href.indexOf(link)!=-1){
                        $('#mobile_menu').append('<option value="'+link+'" selected="selected">'+text+'</option>');
                    } else{
                        $('#mobile_menu').append('<option value="'+link+'">'+text+'</option>'); 
                    }
                });
                $('#mobile_menu').live('change', function(){
                    if($(this).val()!=''){
                        window.location = $(this).val();
                    }
                });
                $(' .slide-container>a').each( function() { 
                    $(this).hoverdir({
                        hoverDelay : 75
                    });
                });
                $(' .portfolio-link ').each( function() { 
                    $(this).hoverdir({
                        hoverDelay : 75
                    });
                });
                
                $('.slide-container>a, .portfolio-link').touchTouch();
                if(navigator.platform.indexOf("iPhone") != -1 || navigator.platform.indexOf("iPad") != -1 || navigator.platform.indexOf("iPod") != -1){
                    jQuery('#filter').addClass('iphone_select');
                }
                $('#filter').selectik({maxItems: 8},
                {
                    _generateHtml: function(){
                        this.$collection = this.$cselect.children();
                        var html = '';
                        for (var i = 0; i < this.$collection.length; i++){
                            var $this = $(this.$collection[i]);
                            var textOption = $this[0].text;
                            var valueOption = $this[0].value;
                            html += '<li class="'+ ($this.attr('disabled') === 'disabled' ? 'disabled' : '') +' new" data-value="'+valueOption+'">'+textOption+'</li>';
                        };
                        return html;
                    }
                }
            ); 
                
                
                var window_width = $(window).width();


                if ($.fn.cssOriginal!=undefined)
                    $.fn.css = $.fn.cssOriginal;

                $('.banner').revolution(
                {
                    delay:9000,
                    startheight:560,
                    startwidth:1400,


                    hideThumbs:200,

                    thumbWidth:100,							// Thumb With and Height and Amount (only if navigation Tyope set to thumb !)
                    thumbHeight:50,
                    thumbAmount:5,

                    navigationType:"verticalcentered ",				// bullet, thumb, none
                    navigationArrows:"nexttobullets",				// nexttobullets, solo (old name verticalcentered), none

                    navigationStyle:"navbar",				// round,square,navbar,round-old,square-old,navbar-old, or any from the list in the docu (choose between 50+ different item), custom


                    navigationHAlign:"center",				// Vertical Align top,center,bottom
                    navigationVAlign:"bottom",					// Horizontal Align left,center,right
                    navigationHOffset:0,
                    navigationVOffset:20,

                    soloArrowLeftHalign:"left",
                    soloArrowLeftValign:"center",
                    soloArrowLeftHOffset:20,
                    soloArrowLeftVOffset:0,

                    soloArrowRightHalign:"right",
                    soloArrowRightValign:"center",
                    soloArrowRightHOffset:20,
                    soloArrowRightVOffset:0,

                    touchenabled:"on",						// Enable Swipe Function : on/off
                    onHoverStop:"on",						// Stop Banner Timet at Hover on Slide on/off

                    stopAtSlide:-1,							// Stop Timer if Slide "x" has been Reached. If stopAfterLoops set to 0, then it stops already in the first Loop at slide X which defined. -1 means do not stop at any slide. stopAfterLoops has no sinn in this case.
                    stopAfterLoops:-1,						// Stop Timer if All slides has been played "x" times. IT will stop at THe slide which is defined via stopAtSlide:x, if set to -1 slide never stop automatic

                    hideCaptionAtLimit:0,					// It Defines if a caption should be shown under a Screen Resolution ( Basod on The Width of Browser)
                    hideAllCaptionAtLilmit:0,				// Hide all The Captions if Width of Browser is less then this value
                    hideSliderAtLimit:0,					// Hide the whole slider, and stop also functions if Width of Browser is less than this value

                    shadow:0,								//0 = no Shadow, 1,2,3 = 3 Different Art of Shadows  (No Shadow in Fullwidth Version !)
                    fullWidth:"on"							// Turns On or Off the Fullwidth Image Centering in FullWidth Modus


                });
                
                $('.view-mode a').click(function(e){
                    e.preventDefault();
                    $('.view-mode a').removeClass('active');
                    $(this).addClass('active');
                    if($(this).hasClass('view-mode-list')){
                        $('.portfolio-container .column').addClass('list-view');
                    } else {
                        $('.portfolio-container .column').removeClass('list-view');
                    }
                    $('.portfolio-container').isotope( 'reLayout');

                });
                
 //      active buttons

            });
            $(window).load(function(){
                "use strict";
                $('#foo4').carouFredSel({
                    responsive: true,
                    width: '100%',
                    auto: false,
                    next:'#car-next',
                    prev:'#car-prev',
                    scroll: 1,
                    items: {
                        width: 240,
                        //	height: '30%',	//	optionally resize item-height
                        visible: {
                            min: 1,
                            max: 3
                        }
                    }
                });
                $(function(){
                    var $container = $('.portfolio-container');
                    $container.isotope({itemSelector : '.element'});
                    var $optionSets = $('#filter'),$optionLinks = $optionSets.find('option');
                    $optionSets.change(function(){
                        var $this = $(this).find('option:selected');
                        
                        //don't proceed if already selected
                        
                        var $optionSet = $this.parents('#filter');
                        $optionSet.find('option[selected="selected"]').removeAttr('selected');
                        $this.attr('selected','selected');
                        // make option object dynamically, i.e. { filter: '.my-filter-class' }
                        var options = {},
                        key = $optionSet.attr('data-option-key'),
                        value = $this.val();
                        console.log(value);
                        // parse 'false' as false boolean
                        value = value === 'false' ? false : value;
                        options[ key ] = value;
                        if ( key === 'layoutMode' && typeof changeLayoutMode === 'function' ) {
                            // changes in layout modes need extra logic
                            changeLayoutMode( $this, options );
                        } else {
                            // otherwise, apply new options
                            $container.isotope( options );
                        }
                        return false;
                    });
                });
                
            });
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43135622-1', 'creo.of.by');
  ga('send', 'pageview');           
        </script>
      
    </body>

</html>
