<table id="taskTable" class="table table-striped table-bordered table-responsive" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Создана</th>
                <th>Название</th>
                <th>Заказчик</th>
                <th>Исполнитель</th>
                <th>Статус</th>
            </tr>
        </thead>    
 
        <tfoot>
            <tr>
                <th>Создана</th>
                <th>Название</th>
                <th>Заказчик</th>
                <th>Исполнитель</th>
                <th>Статус</th>
            </tr>
        </tfoot>
        <tbody>
<?php foreach($this->taskList as $task){?>
     <tr id="div<?= $task['id'] ?>">
         <td>
             <?= date("d.m.y", $task['created_at']); ?>
         </td>
       <td>
           <a href="<?= $this->baseUrl().'/admin/tasks/view/id/'.$task['id']?>">
                <?= $task['title']?>
           </a>    
       </td>
       <td>
           <a href="<?= $this->baseUrl().'/admin/customers/view/id/'.$task['customer_id'] ?>">
                <?= $task['cust_username']." ".$task['cust_surname'] ?>
           </a>
       </td>
       <td>
           <?php if($task['performer_id']){?>
                <a href="<?= $this->baseUrl().'/admin/performers/view/id/'.$task['performer_id'] ?>">
                    <?= $task['per_username']." ".$task['per_surname'] ?>
                </a>
           <?php }else{ ?>
           Не назначен
           <?php }?>
       </td>
       <td>
           <?php switch ($task['status']){
               case "non_taken":
                   echo 'не назначена';
                   break;
               case "taken":
                   echo 'в работе';
                   break;
               default:
               echo "не определен";
               break;
           }?>
       </td>
     </tr>   
<?php } ?>
 </tbody>
</table>
<script>
        $(document).ready(function(){
        $('#taskTable').DataTable();
    });
function removeCategory(id){
    $('#removeBut'+id).remove();
    $('#preloader'+id).show();
$.ajax({
  type: 'POST',
  url: '<?= $this->baseUrl.'/admin/task/remove-task/'; ?>',
  data: {id: id},
  success: function(data){
    $('#preloader'+id).remove();
    $('#div'+id).remove();
  }
});
}
</script>
