<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h3><?= $this->task['title'] ?></h3>
        </div>
        <div class="col-lg-3">
            <?php if( $this->task['task_image'] ){?>
                <img src="<?= $this->baseUrl() ?>/images/task_images/<?= $this->task['task_image'] ?>" width="150px" >
            <?php }else{?>
                <img src="<?= $this->baseUrl() ?>/images/no-image.png" width="150px" >
            <?php } ?>
        </div>
        <div class="col-lg-9">
            <div class="col-lg-12">
                <strong>Заказчик :</strong><a href="<?= $this->baseUrl().'/admin/customers/view/id/'.$this->task['customer_id'] ?>"><?= $this->task['cust_username'].' '.$this->task['cust_surname'] ?></a>
                
            </div>
            <?php if($this->task['status'] != 'non_taken'){?>
            <div class="col-lg-12">
                <strong>Исполнитель :</strong><a href="<?= $this->baseUrl().'/admin/performers/view/id/'.$this->task['performer_id'] ?>"><?= $this->task['per_username'].' '.$this->task['per_surname'] ?></a>
                
            </div>
            <?php } ?>
            <div class="col-lg-12">
                <strong>Статус :</strong><?= $this->task['status'] ?>
                
            </div>
            <div class="col-lg-12">
                <strong>Создана:</strong> <?= date(" d.m.y",$this->task['created_at']) ?>
                
            </div>
            <div class="col-lg-12">
                <strong>Стоимость:</strong> <?= $this->task['customers_price'] ?>
                
            </div>
            <div class="col-lg-12">
                <strong>Описание:</strong> <?= $this->task['description'] ?>
                
            </div>

        </div>
        <div class="col-lg-12">
<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
        <a href="#home" aria-controls="home" role="tab" data-toggle="tab">Отзывы</a>
    </li>
    <li role="presentation">
        <a href="#comments" aria-controls="profile" role="tab" data-toggle="tab">Комментарии</a>
    </li>
 </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
        <div class="col-lg-12">
        
           <?php if($this->task['fp_kind'] || $this->task['fc_kind']){?>
            <div class="col-lg-12">    
                <h2>Отзывы</h2>
            </div>
            <?php if($this->task['fp_kind']){?>
            <div class="col-lg-12">  
                <h3>Исполнитель : </h3>
                <p><?= $this->task['fp_kind'] ?></p>
                <p><?= $this->task['fp_text'] ?></p>
                <p>Оценка: <?= $this->task['fp_rating'] ?></p>
                <p><small><?= date("h:i d.m.y",$this->task['fp_created']) ?></small></p>
            </div>
            <?php } if($this->task['fc_kind']){?>
            <div class="col-lg-12">  
                <h3>Заказчик : </h3>
                <p><?= $this->task['fc_kind'] ?></p>
                <p><?= $this->task['fc_text'] ?></p>
                <p>Оценка: <?= $this->task['fc_rating'] ?></p>
                <p><small><?= date("h:i d.m.y",$this->task['fc_created']) ?></small></p>
            </div>
            <?php }?>
           <?php }else{ ?>
            <h3>Отзывов пока нет</h3>
           <?php } ?>
        


        </div>       
    </div>
      <div role="tabpanel" class="tab-pane" id="comments">
          <?php foreach($this->comments as $comment){?>
          <div class="col-sm-12">
              <div class="col-sm-3">
                  <img width="100" src="<?= $this->baseUrl().'/images/users_images/'.$comment['u_image'] ?>">
              </div>
              <div class="col-sm-3">
                  Пользователь : 
                  <?php if($comment['u_role'] == 'customer'){ ?>
                    <a href="<?= $this->baseUrl().'/admin/customers/view/id/'.$comment['user_from'] ?>">
                          <?= $comment['u_username'].' '.$comment['u_surname'] ?>
                    </a>
                  <?php }else if($comment['u_role'] == 'performer'){ ?>
                    <a href="<?= $this->baseUrl().'/admin/performers/view/id/'.$comment['user_from'] ?>">
                          <?= $comment['u_username'].' '.$comment['u_surname'] ?>
                    </a>   
                  <?php }  ?>
                        <small><?= date("h:i d.m.y", $comment['created']) ?></small>
              </div>
              <div class="col-sm-6">
                  <p><?= $comment['text'] ?></p>
              </div>    
              
          </div>
          <?php } ?>
           <?=  $this->paginationControl($this->comments, 'Sliding', 'pagination.phtml') ?>
      </div>
  </div>

</div>        
 
    </div>
    </div>
</div>


